### ISSUE TITLE
out of the box incompatible with current sveltekit scaffolding

### ISSUE THREAD

**Issue by student020341** [josdejong/svelte-jsoneditor#1]
Not sure if this is an issue, but when I make a new project using "npm init svelte@next" and use this module using "npm install svelte-jsoneditor" and try to use it, I see this error:
```
Must use import to load ES Module: C:\Users\tom\Desktop\stuff\sc\client\node_modules\svelte-jsoneditor\dist\jsoneditor.js require() of ES modules is not supported. require() of C:\Users\tom\Desktop\stuff\sc\client\node_modules\svelte-jsoneditor\dist\jsoneditor.js from C:\Users\tom\Desktop\stuff\sc\client\node_modules\@sveltejs\kit\dist\index2.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules. Instead rename jsoneditor.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from C:\Users\tom\Desktop\stuff\sc\client\node_modules\svelte-jsoneditor\package.json.

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: C:\Users\tom\Desktop\stuff\sc\client\node_modules\svelte-jsoneditor\dist\jsoneditor.js
require() of ES modules is not supported.
require() of C:\Users\tom\Desktop\stuff\sc\client\node_modules\svelte-jsoneditor\dist\jsoneditor.js from C:\Users\tom\Desktop\stuff\sc\client\node_modules\@sveltejs\kit\dist\index2.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename jsoneditor.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from C:\Users\tom\Desktop\stuff\sc\client\node_modules\svelte-jsoneditor\package.json.

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1080:13)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at load_node (C:\Users\tom\Desktop\stuff\sc\client\node_modules\@sveltejs\kit\src\api\dev\loader.js:137:22)
    at get_module (C:\Users\tom\Desktop\stuff\sc\client\node_modules\@sveltejs\kit\src\api\dev\loader.js:20:26)
    at C:\Users\tom\Desktop\stuff\sc\client\node_modules\@sveltejs\kit\src\api\dev\loader.js:108:27
    at Array.map (<anonymous>)
    at initialize_module (C:\Users\tom\Desktop\stuff\sc\client\node_modules\@sveltejs\kit\src\api\dev\loader.js:107:10)
    at C:\Users\tom\Desktop\stuff\sc\client\node_modules\@sveltejs\kit\src\api\dev\loader.js:47:22
    at C:\Users\tom\Desktop\stuff\sc\client\node_modules\@sveltejs\kit\src\api\dev\loader.js:108:21
    at async Promise.all (index 2)
    at initialize_module (C:\Users\tom\Desktop\stuff\sc\client\node_modules\@sveltejs\kit\src\api\dev\loader.js:106:8)
    at C:\Users\tom\Desktop\stuff\sc\client\node_modules\@sveltejs\kit\src\api\dev\index.js:318:32
    at get_response (C:\Users\tom\Desktop\stuff\sc\client\node_modules\@sveltejs\kit\src\renderer\page.js:141:16)
```

Not sure if this is a svelte problem, a sapper/sveltekit problem or what, just something to note that users seeking the bleeding edge of technology might run into this wall. 

Steps to reproduce:
1. `npm init svelte@next`
2. `npm install svelte-jsoneditor `
3. follow the basic usage example for svelte, just importing it in your component will yield the above

-- additional info

Maybe this is just my misunderstanding. I tried npm installing the previous jsoneditor and am having similar issues. Are these projects not usable as npm packages? Or is sveltekit/sapper completely busted?

-- more info

Good/bad news! After some additional testing (creating a new svelte project without sveltekit), following the example for svelte-jsoneditor worked. It is probably fine to attribute these errors to sveltekit or its bundler snowpack, and hopefully that is not indicative of impending disaster when sveltekit is stable 👍

**Comment by josdejong** [comment]
Thanks for bringing this up @student020341 ! 

This is the first ever project I do with Svelte, it can very well be that I haven't set up everything correctly.

Anyone able to help out here to improve the library set up? Help would be very welcome.

**Comment by student020341** [comment]
I wish I could offer some kind of suggestion, but sveltekit is riddled with warnings about how things are unstable and will be changing. It's more of an alpha at this point, the advantage of using it is being able to pick typescript and sass out of the box with a different build tool :)

The stable version of svelte does not throw this error, so for now this issue is more awareness than anything else. If it's not actionable or worth the effort to fix something for an unstable version of svelte, might make sense to close this issue for now and check again when sveltekit is at least in beta.

**Comment by josdejong** [comment]
Ah, ok, I hadn't realized this is about SvelteKit which isn't officially published yet! 

Shall we close this issue, and open a new ticket as soon as SvelteKit is published?

**Comment by student020341** [comment]
Yes, my bad for jumping the gun.

**Comment by josdejong** [comment]
I appreciate your inputs, thanks 👍
