### ISSUE TITLE
Disable Menu on readOnly

### ISSUE THREAD

**Issue by on2air** [josdejong/svelte-jsoneditor#10]
Looks like there is support for a readOnly param (although its not in the documentation). Seems to work fine, except the menu still has all the options to modify everything - they just don't do anything.

Can we disable the popup menu items related to modifying the data when in readOnly mode

**Comment by josdejong** [comment]
Yes thats true, I started implementing a `readOnly` property, but stopped it halfway to address feedbacks on the published beta of the JSON editor. Once it is finished I'll add the feature to the documentation.

**Comment by josdejong** [comment]
The `readOnly` option is now fully implemented and documented in `0.1.6`.
