### ISSUE TITLE
How do I get rid of the CodeMirror text?

### ISSUE THREAD

**Issue by bostondevin** [josdejong/svelte-jsoneditor#100]
How do I get rid of the CodeMirror text?

**Comment by bostondevin** [comment]
Aha - .jse-contextmenu {display: none}

But is this OK to do?

**Comment by josdejong** [comment]
I guess it's OK to remove. Important though is to keep attribution for all used open source projects in place one way or another. It's indeed not really interesting for the user, though I just want to express my gratitude this way 😄.
