### ISSUE TITLE
Clicking light grey value placeholder on a new key in tree mode makes new key disappear

### ISSUE THREAD

**Issue by bostondevin** [josdejong/svelte-jsoneditor#101]
Clicking light grey value placeholder on a new key in tree mode makes new key disappear - it should focus into the new blank field where the grey value placeholder was. Otherwise you have to know to use the tab key...

**Comment by josdejong** [comment]
I'm not entirely sure what you mean. When clicking a key or value placeholder, it gets focus and will be displayed with a gray background. When selected, you indeed do not see the placeholder text, is that what you mean?
