### ISSUE TITLE
How to add font awesome classes for icons instead of svg?

### ISSUE THREAD

**Issue by bostondevin** [josdejong/svelte-jsoneditor#103]
I was looking to make the buttons use font awesome classes: <i class="fas fa-home"></i> instead of the SVG's - any way to achieve this?

**Comment by josdejong** [comment]
I don't know. I'm using https://github.com/RobBrazier/svelte-awesome for the icons.

What is the reason you need classes instead of SVG icons?

**Comment by josdejong** [comment]
Will close this issue due to lack of response. Feel free to reopen if needed.
