### ISSUE TITLE
Submenu button menu icon's aren't disabled when associated button is in context menu

### ISSUE THREAD

**Issue by bostondevin** [josdejong/svelte-jsoneditor#105]
In the context menu, when certain buttons are disabled (cut, copy, edit value), their associated submenu arrow isn't, when it should be. I would just hide the buttons altogether if they are disabled.

**Comment by josdejong** [comment]
Yes good point, thanks for your suggestion.

**Comment by josdejong** [comment]
Fixed now in `v0.4.0`
