### ISSUE TITLE
Colorize numbers and timestamps differently for usability

### ISSUE THREAD

**Issue by bostondevin** [josdejong/svelte-jsoneditor#106]
Currently a number (123) and a timestamp number (1655732094189) are highlighted in red - it would be nicer if they were colored differently for usability. Possibly blue for timestamps?

I do see nice tooltips giving the localized human readable date on hover which is great!

**Comment by josdejong** [comment]
I think this is a bit of a personal preference. I do like that it still has the same color as numbers, and timestamps to show am icon on the right side, that's also a clear distinction to me. Similarly, urls still have the same green color as strings but are underlined to make a distinction.

![afbeelding](https://user-images.githubusercontent.com/568626/175047866-c4ac6449-7a7c-432a-b53c-e1439d3257e2.png)

At least, it may be neat to introduce a css class for it so you can customize the styling if you want.
