### ISSUE TITLE
Auto sort keys?

### ISSUE THREAD

**Issue by bostondevin** [josdejong/svelte-jsoneditor#109]
Is there a way to somehow call the sort function when it loads to auto-sort the keys?

**Comment by josdejong** [comment]
You can sort keys via the "Sort" modal. 

The editor does not make changes to the document you load, which is on purpose. I think the user should be in control.

If you want to automatically sort keys beforehand, you can maybe do that yourself before loading the JSON in the editor?

**Comment by josdejong** [comment]
Closing this issue due to lack of response. Please reopen if needed.
