### ISSUE TITLE
Dependency issue with SvelteKit + Vite v3

### ISSUE THREAD

**Issue by lowlandghost** [josdejong/svelte-jsoneditor#117]
Hi there,

I am running into an issue when using Sveltekit + Vite when trying to import this package to use on a page. I get an `SyntaxError: Unexpected token 'export'` which seems to be related to the use of `@fortawesome/free-solid-svg-icons/index.es.js:9470`

```
SyntaxError: Unexpected token 'export'
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1026:15)
    at Module._compile (node:internal/modules/cjs/loader:1061:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1151:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:168:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:197:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:337:24)
```

The page contents:

```
<script>
	import { JSONEditor } from 'svelte-jsoneditor'

       let content = {}
</script>

<div>
	<JSONEditor bind:content />
</div>
```

It even happens without me adding the <JSONEditor> tag altogether. 

Let me know if there is any more info I can pass along to help out. Thank you :)

I have also tried disabling SSR and wrapping the component around a browser if statement as well.

<details>
<summary>Package versions</summary>

```
├── @fortawesome/free-regular-svg-icons@6.1.2
├── @fortawesome/free-solid-svg-icons@6.1.2
├── @sveltejs/adapter-auto@1.0.0-next.63
├── @sveltejs/kit@1.0.0-next.394
├── @tailwindcss/forms@0.5.2
├── autoprefixer@10.4.7
├── cookie@0.5.0
├── eslint-config-prettier@8.5.0
├── eslint-plugin-svelte3@4.0.0
├── eslint@8.20.0
├── lucide-svelte@0.75.0
├── postcss-load-config@4.0.1
├── postcss@8.4.14
├── prettier-plugin-svelte@2.7.0
├── prettier@2.7.1
├── sass@1.54.0
├── svelte-check@2.8.0
├── svelte-jsoneditor@0.5.0
├── svelte-popperjs@1.2.11
├── svelte-portal@2.2.0
├── svelte-preprocess@4.10.7
├── svelte@3.49.0
├── tailwindcss@3.1.6
├── typescript@4.7.4
└── vite@3.0.3
```

</details>

**Comment by josdejong** [comment]
Thanks for reporting. How can I reproduce your issue? I gave it a try but without success.

**Comment by josdejong** [comment]
I can now reproduce this issue in the latest version of SvelteKit and Vite. This is an old issue popping up again because the workaround doesn't work anymore.

See https://github.com/josdejong/svelte-jsoneditor/issues/107#issuecomment-1198219931. 

Let's continue the discussion there and close this as a duplicate.
