### ISSUE TITLE
Expose editor's root element ref, onMount callback

### ISSUE THREAD

**Issue by plibither8** [josdejong/svelte-jsoneditor#12]
Hey! It would be great and really convenient if the `refJsonEditor` (https://github.com/josdejong/svelte-jsoneditor/blob/main/src/components/JSONEditor.svelte#L50) variable could be `export`ed so users can use it for DOM manipulation.

Further, exposing an a callback for `onMount` that calls the callback in the `onMount()` of the component will be great too!

Thanks again :)

**Comment by josdejong** [comment]
Thanks for your suggestions 👍  

1. I'm not sure if a reference to the DOM would be an often used feature. Can you explain why you need it? 
    There is an easy workaround at least: when you need this ref, you can wrap the editor in a `div`, get the ref of this `div`, then the first child in this `div` is the editor.
2. Can you explain why you need an `onMount` callback? I can imagine it could be useful but I would like to understand the use case.

**Comment by josdejong** [comment]
Will close this issue now due to inactivity, please reopen when still relevant.
