### ISSUE TITLE
Allow copy node's path

### ISSUE THREAD

**Issue by elvuel** [josdejong/svelte-jsoneditor#13]
> Could be copy on ContextMenu or emit on `mousedown`.

**Comment by josdejong** [comment]
Thanks, good suggestion. I think this should be an explicit button in the ContextMenu, and possibly also a quick key.

**Comment by elvuel** [comment]
@josdejong how about copy `JSONPath` instead of or over slice?

**Comment by josdejong** [comment]
Good point about what format to use: JSONPath, JSONPointer, JavaScript notation...

An other idea: I also want to implement a path (like "bread crumbs" on top, like in the old editor:

![afbeelding](https://user-images.githubusercontent.com/568626/123516373-0a3dda00-d69c-11eb-84ae-7dde2eb49301.png)

We could also make the copy button _there_.

**Comment by josdejong** [comment]
Another idea it would be nice if you could paste a path too, and then scroll towards this path in the document.

**Comment by dranitski** [comment]
vote up for copy node path button near the breadcrumbs. Very handy and easy to implement :+1:

**Comment by feidhlimx** [comment]
Hi, I had to recently work around this issue by getting the path from a selected node through onChange (patchResult.from) function then reverting the changes in the document - basically making the doc readOnly but keeping the editable state in order to get the currently selected path.
This fix to the API would be really helpful, as the info is already on hand...
The path should be available on the API onClick or something similar...

**Comment by josdejong** [comment]
I'm working on this feature right now. 

I was wondering: what kind of path notation do you guys use? A JSON Path like `$.data[2].nested.property`, or JSON Pointer like `/data/2/nested/property`?

**Comment by dranitski** [comment]
@josdejong thanks a lot! I guess any will be fine if we can easily parse, split, modify it as we want. Some kind of trigger (onNodePathCopy) will be cool.

personally I like the first one `$.data[2].nested.property`

**Comment by josdejong** [comment]
Yes I prefer a notation like `$.data[2].nested.property` better too. I'll start with that.

What would be the use case for a `onNodePathCopy` callback?

**Comment by josdejong** [comment]
Yes, that makes sense. I have a PR #164 ready. I have implemented a new option `pathParser: { parse, stringify }`, allowing you to customize how the path is parsed/stringified. By default it uses a JSON Path notation, but you can configure it to use JSON Pointer instead or anything you want.

**Comment by josdejong** [comment]
First version now published in `v0.7.10`.

Feedback is very welcome, I can imagine there are good ideas to refine this solution further.

**Comment by feidhlimx** [comment]
> What would be the use case for a `onNodePathCopy` callback?

It would be nice to have the JSON path value through the API - on the current selected node, not just after a copy.

This would basically be the same info that is displayed in the navigation bar, but in the API.

How could I achieve this?

**Comment by josdejong** [comment]
@feidhlimx there are plans to implement an API to get and set the selection, see #163. I think that will address your suggestion.
