### ISSUE TITLE
CSS Broken on editor page

### ISSUE THREAD

**Issue by PsyGik** [josdejong/svelte-jsoneditor#136]
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/5432911/187960993-af2d40ab-cbd3-42df-b6ce-0a554b2ad135.png">

**Comment by josdejong** [comment]
Thanks for reporting. This should be solved after refreshing your page with F5 or Ctrl+F5. 

Sorry for the inconvenience, I did an update, apparently there are some caching issues.

**Comment by PsyGik** [comment]
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/5432911/188083332-e950ecb5-a623-44c5-8444-a637cd36db9d.png">

can confirm the CSS load now. Closing this. Thank you

**Comment by josdejong** [comment]
Good to hear 👍, thanks for the feedback
