### ISSUE TITLE
[QUESTION] Is there a variable to control the colors of error popup? Or a dark mode for it?

### ISSUE THREAD

**Issue by shakhbulatgaz** [josdejong/svelte-jsoneditor#138]
Hello, hope you are doing well.

I can't find a variable that controls the background color and font color of an error popup (see screenshot).
More so, it appears that even https://jsoneditoronline.org/, which uses this library, could not change these properties (the screenshot is from there).

_Can_ you change these properties currently?
If not, can you turn the popup off?

Thank you for your time.

![image](https://user-images.githubusercontent.com/22275982/189297562-ca411b0b-eebc-4403-b3b6-0359c620b5b1.png)

**Comment by shakhbulatgaz** [comment]
Using a debugger. It turns out that this popup does not use any variables, but you can probably set the properties by using '.cm-tooltip' class.

Please confirm

![image](https://user-images.githubusercontent.com/22275982/189299716-334a82f7-2d8b-4aa4-bce4-c2a00cb2f85f.png)

**Comment by josdejong** [comment]
Good point! The tooltip text is not readable in dark mode. I'll fix that and introduce a couple of additional css variables.

You're right, you can apply styling yourself by using the `cm-tooltip` class for example.

**Comment by josdejong** [comment]
Note that there are two types of tooltips: error and warning. The latter is used when having JSON schema validation errors.

**Comment by shakhbulatgaz** [comment]
Thank you, have a good day.

**Comment by josdejong** [comment]
The styling of the tooltip in dark mode is now fixed in v0.7.4
