### ISSUE TITLE
Can't use numpad keyboard for entering numbers in tree mode

### ISSUE THREAD

**Issue by homayoonahmadi** [josdejong/svelte-jsoneditor#139]
Hi there,
I enjoyed your project and appreciate that, but when I want to enter numbers in tree mode it doesn't accept numbers from numpad and I have to use numbers placed in top of main keyboard characters instead, and it's bothering.

What can I do to fix this?

**Comment by josdejong** [comment]
I just tested and I see that numpad indeed only partially works: when double-clicking to start editing an existing value I can use the numpad, only to insert a new field or replace an existing field I cannot use keys from the numpad. Is that what you mean?

**Comment by homayoonahmadi** [comment]
Yes, I have to double click on values actually. Its boring for editing fields; I just want to go to next value using arrow keys (up and down keys) and enter numbers without having to double click on it every time.

Thanks in advance
