### ISSUE TITLE
Urgent problem of partial modify and provide delete function

### ISSUE THREAD

**Issue by MichaelPanwenjie** [josdejong/svelte-jsoneditor#140]
I am using jsonedit to add, delete, check and change mongodb data in the angular project.
What I want now is ：

1.Let jsonedit only can modify value, can not modify keys,
2.You cannot add data structures. You can delete some structures, but you cannot add additional ones
3.Jsonedit has the function of remove
4. Verify data validity

How do you realize this requirement？can give me a simple, thanks!

**Comment by josdejong** [comment]
Though it's on the wish-list, the library does not have ways to have partially editable/readonly contents. 

You can use JSON schema or a custom validator to validate your data.
