### ISSUE TITLE
Is it possible to disable the auto-beautification of the edited JSON? 

### ISSUE THREAD

**Issue by Flixbox** [josdejong/svelte-jsoneditor#146]
I have a JSON file that is saved in a very specific way in order to track which keys were changed in specific commits and send updates to a Discord channel. In order to create an easy-to-use editor for this JSON, I'd like to build an electron app using this library. However, since the JSON has to keep its format, I'm wondering if this library would be an option since every example I've come across has auto-beautified the JSON. Is there any configuration I can set that would avoid this behaviour?

Here's the file I'd like to create a handy editor for: https://github.com/Flixbox/lp-compat/blob/main/static/compat-data/apps.json

I'm definitely open to other ideas as well!

// Update: I've simply written a Discord bot, which matches my use case a bit better. Feel free to close this issue if no one else needs this information 🚀

**Comment by josdejong** [comment]
Right now, only by using `text` mode you can keep the formatting as it is. In `tree` mode, the editor parses the JSON document into memory, and there it has no formatting. That is the reason that when saving it afterwards, it will format it again. 

Right now, you can only specify the indentation, but not something in your example where only the root level objects have indentation and newlines, and the nested objects/arrays are minified. 

Two thoughts:
- I'm working on a big new feature right now that will allow you to pass a custom JSON parser. That would enable passing your own `JSON.stringify` function with your own formatting. 
- For your specific case, I can imagine that you get the compacted JSON from the editor, and then write a little regexp to add indentation to the root level object: replace all occurrences of `'},"'` with `'},\n  "'`, and write two similar matches for the first and last line.

**Comment by Flixbox** [comment]
Sounds good to me! I'll wait until the parser is finished and then think some more about my use case.
