### ISSUE TITLE
Spacing issue on the editor when changing mode from tree to text mode in the vanilla-jsoneditor 

### ISSUE THREAD

**Issue by KishanRavindran** [josdejong/svelte-jsoneditor#158]
I have installed the vanilla-jsoneditor in my angular 13 application and I am able to get the editor displayed. But when I try to change the mode to text mode the view is changed to as in below . Is there a way to resolve spacing in the editor and content.  
![Jsoneditor_text_mode](https://user-images.githubusercontent.com/22557988/194333744-017227b1-c62f-4831-aebf-9e6053202f4d.png)

**Comment by josdejong** [comment]
It looks like the CSS of the text editor is broken. On https://jsoneditoronline.org/ you can see how it is supposed to look. How can I reproduce your issue?

**Comment by KishanRavindran** [comment]
I have installed this package in angular 13 with clarity web component. I will try to see what is the CSS issue if I try to put the code in stackblitz.

**Comment by josdejong** [comment]
I'll close this issue now: not enough information to reproduce or conclude that there is a bug in the library. Please reopen when needed.
