### ISSUE TITLE
Failing to build within NextJS project

### ISSUE THREAD

**Issue by stringa** [josdejong/svelte-jsoneditor#16]
Hello, I was super excited to see this project. I've been using the original version within my project and it does have it quarks. My steps for repo:

0) use a nextJS project (typescript)
1) npm install svelte-jsoneditor
2) npm install --save-dev @rollup/plugin-json svelte-preprocess sass
3) add ./rollup.config.js to the root
4) Add import { JSONEditor } from "svelte-jsoneditor"; to my component
5) Add  <JSONEditor json={{}} /> in my render() function
6) run 'npm run build'

Errors:

> Build error occurred
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /Users/sean.stringer/dev/skinconfig.admin/node_modules/svelte-jsoneditor/dist/jsoneditor.js
require() of ES modules is not supported.
require() of /Users/sean.stringer/dev/skinconfig.admin/node_modules/svelte-jsoneditor/dist/jsoneditor.js from /Users/sean.stringer/dev/skinconfig.admin/dist/.next/server/pages/skinconfig.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename jsoneditor.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /Users/sean.stringer/dev/skinconfig.admin/node_modules/svelte-jsoneditor/package.json.

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:13)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.lfQ6 (/Users/sean.stringer/dev/skinconfig.admin/dist/.next/server/pages/skinconfig.js:240:18)
    at __webpack_require__ (/Users/sean.stringer/dev/skinconfig.admin/dist/.next/server/pages/skinconfig.js:23:31)
    at Module.qmwh (/Users/sean.stringer/dev/skinconfig.admin/dist/.next/server/pages/skinconfig.js:288:35)
    at __webpack_require__ (/Users/sean.stringer/dev/skinconfig.admin/dist/.next/server/pages/skinconfig.js:23:31)
    at Object.21 (/Users/sean.stringer/dev/skinconfig.admin/dist/.next/server/pages/skinconfig.js:120:18) {
  type: 'NodeError',
  code: 'ERR_REQUIRE_ESM'
}

As you can see I'm getting a ERR_REQUIRE_ESM error. The message is telling me to do a couple things different.

Has anyone run into this issue?

**Comment by stringa** [comment]
Looks like i should be able to use next-transpile-modules, but I can't seem to get that working with my webpack config. Stuck at that point.

**Comment by josdejong** [comment]
Thanks, glad to hear you like this new library :)

Few feedbacks:

1. Only for Svelte projects the `npm install --save-dev @rollup/plugin-json svelte-preprocess sass` and config stuff is needed, in other projects (like React or so) you can simply use the provided bundles.
2. Looking at your stacktrace I see that `svelte-jsoneditor/dist/jsoneditor.js` is being loaded. This is the CommonJS bundle. Looking at the error message, you're setup expects ES modules. This is provided as `svelte-jsoneditor/dist/jsoneditor.mjs`. You can try to import that bundle explicitly: `import { JSONEditor } from "svelte-jsoneditor/dist/jsoneditor.mjs"`
3. the library can't be rendered server side, I'm not sure if you need to configure something for that in your nextjs project.

**Comment by stringa** [comment]
Thanks for the quick response. npm installed and the files seem there, for some reason it's not picking up the mjs file.

**Comment by stringa** [comment]
Is there possibly a rollup config that would work better?

**Comment by josdejong** [comment]
But does the `import { JSONEditor } from "svelte-jsoneditor/dist/jsoneditor.mjs"` work for you in the first place?

The library has the following entry points in `package.json`:

```
  "svelte": "src/index.js",
  "module": "dist/jsoneditor.mjs",
  "main": "dist/jsoneditor.js",
  "browser": "dist/jsoneditor.js",
```

As far as I know, the `main` should point to a CommonJS bundle (for node.js), the `browser` to a bundle that can be loaded in the browser (like UMD), and the non-standard `module` points to the ES module version which you need. I'm not sure what logic nextjs uses to load a library. I can imagine it conflicts with the expectations of other bundlers and frameworks. Do you have an example of a few libaries which _do_ work correctly with nextjs so we can have a look at those?

**Comment by josdejong** [comment]
I think I may know where the issues stem from: `"main": "dist/jsoneditor.js"` is pointing to a .js file containing CommonJS, but the library was configured as `"type": "module:"`, so the expectancy is that .js files contain ES modules.

In `svelte-jsoneditor@0.2.1` there is now only one bundle left: ES module. I expect this will solve the issue. 

Can you give it a try @stringa?

**Comment by stringa** [comment]
Getting much closer. Now i'm just working with undefines:

> Build error occurred
TypeError: Cannot read property 'ace' of undefined
    at /Users/sean.stringer/dev/skinconfig.admin/dist/.next/server/pages/index.js:259:20556

**Comment by stringa** [comment]
If I turn off SSR for that component, I'm able to finally build the project. 

import dynamic from "next/dynamic";
const DynamicComponent = dynamic(() => import("svelte-jsoneditor/dist/jsoneditor"), { ssr: false });

I'm not able to currently load the project though at runtime:

Getting the following:
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `ForwardRef(LoadableComponent)`.

**Comment by josdejong** [comment]
@stringa thanks for taking the time to try it out 👍  

The `dist/jsoneditor.js` bundle is an ES bundle and does export everything, I'm quite sure of that. For example the library is used and deployed in a React application https://jsoneditoronline.org/beta/ right now.

Is it possible to create a small demo nextjs project that I can use to reproduce the issue? (I have zero experience with nextjs)

**Comment by stringa** [comment]
Sure. A basic next app is as simple as creating react apps. https://nextjs.org/docs/api-reference/create-next-app can create an app in a couple seconds and then opening Index.tsx and dropping the import and tag into the Functional Component is about all that is needed to test. 

I've gone ahead and did that and pushed up something here: https://github.com/stringa/next-jsoneditor-test

**Comment by josdejong** [comment]
Thanks. The example doesn't contain `svelte-jsoneditor` itself. I gave it a try, installing the library. I managed to get it working in a very quick-and-dirty way without any "special" magic. What I needed to do was:

- Create a wrapper component which wraps the native JavaScript class in to a React component (Plain JS usage: https://github.com/josdejong/svelte-jsoneditor#standalone-bundle-use-in-react-vue-angular-plain-javascript-).
- Import `'svelte-jsoneditor/dist/jsoneditor.js'`, not `'svelte-jsoneditor'` (for some reason it resolves to the svelte index file otherwise).
- Import the jsoneditor async, using `import(...).then({ JSONEditor} => { ... })`. This is needed to make sure the code is not loaded server side. Without it I got issues that the server side tries to load the code as CommonJS instead of ES module amongst others.

All in all it requires some React plumbing with useEffect, useState, useRef to get all of that sorted. I didn't take the time to figure out all details. I would expect that the async import is not needed, but it would require time to investigate why that gives issues with nextjs (which tries to load as CommonJS then)

**Comment by josdejong** [comment]
I also generated a commonjs bundle (*.cjs) to see if that would work, and load that with a regular import. Then I get an error "TypeError: Cannot read property 'ace' of undefined" which sounds like nextjs is loading it server side without respecting the async import in the JSONEditor bundle. I don't have time right now to go more indepth into next.js, sorry.

**Comment by stringa** [comment]
Awesome. Thanks. Next has a dynamic() keyword which is very similar. I was trying this before with the old library and was never able to get that working. I will try again.

**Comment by stringa** [comment]
I had a quick question I put in issues on the old library (under issues) as I was trying to work with the custom context menu and I would love to get a tip or two on that.

**Comment by josdejong** [comment]
It would be nice to put together a full React and/or Next.js example. 

Anyone interested in working that out?

**Comment by stringa** [comment]
Using the hits for next 11.0.2 canary, i was able to get it working pretty quickly with svelte-jsoneditor@0.1.6 

https://github.com/stringa/next-jsoneditor-test/commit/d89ca0b83f33ea5f4eaf2bd9dc719061e1d06285?branch=d89ca0b83f33ea5f4eaf2bd9dc719061e1d06285&diff=split

**Comment by josdejong** [comment]
Thanks for the update 👍 


I checked out your example repo and upgraded to the latest `svelte-jsoneditor@0.2.7`, this also works fine, except that you have to add the `.js` extension to the import else it says `Module not found: Package path ./dist/jsoneditor is not exported`

So indeed the trick is to load with `async import`, from your code example:

```js
import React from "react";



export default class Editor extends React.Component<any, any> {
    async componentDidMount() {

        const {JSONEditor} = await import('svelte-jsoneditor/dist/jsoneditor.js');

        const container = document.getElementById("jsoneditor");

        let editor = new JSONEditor({
            target: document.getElementById('jsoneditor'),
            props: {
                json: {
                    greeting: 'Hello World',
                }}
        });
    }
    render() {
        return <>
            <p>Editor</p>
            <div id="jsoneditor" />
        </>

    }
}
```

On a side note: I think it would be better to use a React `ref` instead of `<div id="jsoneditor">`: the current approach will have an issue when you try to create two JSONEditors at the same time.

I guess we can close this issue now?
