### ISSUE TITLE
Convert Structure throws an error, can't convert to Object or Array

### ISSUE THREAD

**Issue by wernerstucky** [josdejong/svelte-jsoneditor#160]
On the classic JSON editor one of the functions we used a lot was converting between types.
It seems this conversion is not working on the new version (see video clip)

If you try to convert a string type into an Array or Object you get a the following error : 
```
SyntaxError : JSON value expected but reached end of input at position 0

```

[jsoneditor convert type bug-2022-10-10_07.38.45.webm](https://user-images.githubusercontent.com/2656247/194804465-5ec24a6a-b3e2-4695-8c89-bc7d5daccc0c.webm)

**Comment by josdejong** [comment]
Fixed now in `v0.7.11`
