### ISSUE TITLE
Clicking on color picker causes a form submit

### ISSUE THREAD

**Issue by elipp** [josdejong/svelte-jsoneditor#162]
I'm currently working on integrating this to a Django admin view, and I noticed that clicking on the colored square on the color picker widget causes the form "submit" action to be issued, reloads the page etc.

If this is a feature, I'd love to know how to disable it. Thanks!

**Comment by josdejong** [comment]
Thanks for reporting. This is a bug, this button is missing a `type="button"` attribute.

**Comment by josdejong** [comment]
This issues is fixed now in `v0.7.10`
