### ISSUE TITLE
vanilla-jsoneditor in commonjs

### ISSUE THREAD

**Issue by hacknlove** [josdejong/svelte-jsoneditor#165]
I would like to be able to import vanilla-jsoneditor in my commonjs project.

In the development environment I have been able to workaround this with `import()` but somehow after building it fails.

I have tried to fork the repo and compile it myself to commonjs, but I failed.

I have also tried many other workarounds, and nothing has worked so far.

My two last options are:
1. ask this.
2. look for any alternative library

But I like svelte-jsoneditor, you nailed it. It's real good UX.

So, please, could you bundle it in commonjs too?

Thanks.

**Comment by josdejong** [comment]
Thanks for your suggestion, glad to hear you like the library :)

I'm open to publishing for example an UMD (or CommonJS) version of the library if there is enough need for it. I'm a bit hesitant though: I haven't done that so far, hoping we don't need it nowadays. I would love to get the JavaScript world out of the difficult CommonJS/ESM hybrid situation where we currently are. I think we should all move to ESM as quick as possible.

For the time being, here some ideas for workarounds:

1. The `index.js` file in `vanilla-jsoneditor` is a single, standalone file with a single `export` at the end of the file. To turn it into CommonJS, all you have to do is replace the `export{...}` with `module.exports={...}`. You can write a script reading the file, use a regex to replace the export, and write it in a different file.
2. With for example browserify, you can create an UMD bundle:

    ```
    npm install --save-dev browserify esmify browser-resolve
    npx browserify ./node-modules/vanilla-jsoneditor/index.js -p esmify -o ./jsoneditor.umd.js --standalone jsoneditor
    ```

    Then you can load the output in a browser (or load as CommonJS):

    ```html
    <script src="./jsoneditor.umd.js"></script>
    <script>
      const { JSONEditor } = window.jsoneditor
      // ...
    </script>
    ```
3. There are quite some tools around to convert ESM to CommonJs, maybe there is something else useful around?

**Comment by hacknlove** [comment]
Thanks, it worked.

I didn't see the export at the end of the index. It's minimized. I tried bundling it without the minimizer, but I may have not done it right because I have still got non-readable code.

But I used browserify as you said in 2.

Then I needed to add the types declaration from vanilla-jsoneditor/index.d.ts and lastly to prevent it from being used in the ssr.

:)

**Comment by josdejong** [comment]
👍 that is good to hear.

I understand this is an ugly workaround for you, but I would like to await a bit if there are really more people having the same issue of using a modern ESM module in their project before taking action.

**Comment by hacknlove** [comment]
No worries.

I'm pretty certain this is caused by a poorly typescript configuration from
my side.

And you are right, the only way we speed up the migration to the new
standards is if people stop supporting deprecated shit.

So, having a workaround is more than enough.

**Comment by josdejong** [comment]
Thanks for your understanding.

> And you are right, the only way we speed up the migration to the new standards is if people stop supporting deprecated shit.

😂  I tried to stay polite, but yeah.


I'll close this issue for now, but please feel free to comment or reopen if this turns out to be a common issue.
