### ISSUE TITLE
createAjvValidator fails CSP (Content Security Policy)

### ISSUE THREAD

**Issue by brownieboy** [josdejong/svelte-jsoneditor#168]
I have an app where I'm using the Editor, and am validating with the AJV Validator with this syntax from the Svelte Readme:

```javascript
import { createAjvValidator } from 'svelte-jsoneditor'

const validator = createAjvValidator(schema, schemaDefinitions)
```

It works fine when building locally, but when we push to the server it fails with this error in the browser console:

> Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-eval'

It seems that AJV Validator does some stuff that breaks our CSP when you generate validator functions at runtime in this way.  See this issue on the AJV Validator repo: https://github.com/ajv-validator/ajv/issues/1640

I looked at the workaround linked from that issue https://github.com/ajv-validator/ajv/blob/master/docs/standalone.md.   Apparently, you can use a CLI version to generate your validation function(s) ahead of time and then import them, already compiled.

I'm finding it difficult to follow the logic though.   There doesn't seem to be any direct correlation for the `createAjvValidator(schema, schemaDefinitions)` syntax in any of the code there, for example.

**Comment by josdejong** [comment]
That is an interesting question. So, with the AJV CLI you can generate a JavaScript file containing the validator:

```
ajv compile -s schema.json -o validate_schema.js
```

The next step is to use the generated function and wrap it in a function that outputs the errors in the right format for `svelte-jsoneditor`. There is no need for a factory function since the validator is ready-made:

```js
import validateAjv from './validate_schema.js'

export function myCustomValidator(json: JSONValue): ValidationError[] {
  validateAjv(json)
  const ajvErrors = validateAjv.errors || []

  return ajvErrors.map(improveAjvError).map((error) => normalizeAjvError(json, error))
}
``` 

And then when instantiating a JSONEditor, you can pass your custom validator `myCustomValidator`:

```html
<div>
  <JSONEditor {content} onChange="{handleChange}" validator={myCustomValidator} />
</div>
```

You can copy the functions `improveAjvError` and `normalizeAjvError` from the source code of createAjvValidator if you need it, it is no rocket science:

https://github.com/josdejong/svelte-jsoneditor/blob/b1d820068b92d71207b82281fa51236615d46dc3/src/lib/plugins/validator/createAjvValidator.ts#L45-L79

**Comment by brownieboy** [comment]
Thanks @josdejong .

After posting, I had a look at the source for for the `createAjvValidator` and thought that it might be possible to do what you suggest.

I'll give it a go, anyway.  I'll report back here how I get on.

**Comment by brownieboy** [comment]
Okay, I'm pretty close to having this working now.

I'm following the [Generating functions(s) for multiple schemas using the JS library - ES6 and CJS exports](https://github.com/ajv-validator/ajv/blob/master/docs/standalone.md#generating-functionss-for-multiple-schemas-using-the-js-library---es6-and-cjs-exports) example from the AJV Standalone page.

I had the validator function creation working yesterday, and was able to import and use those functions following your example code ☝️.  Just two issues held me up.

**One Error At A Time**
My major issue, thankfully just solved, as that it would only validate one error at a time in the Editor.  You would fix the first JSON error. just to have another one pop up that you couldn't see before.  This was a terrible UI experience.

I was convinced this was an error in my schema definition config, and have spent nearly day a poring through various functions, many of them upstream, to see where I'd gone wrong.   But it turns out that there's actually an `allErrors` flag that I needed to pass when pre-building the validator functions from the schemas 🤦.

This flag was _not_shown in the example doco.   I found it when searching through the AJV repo issues, here https://github.com/ajv-validator/ajv/issues/1680#issue-939419627  (although it's probably in the API documentation somewhere that I haven't read).

Oh well, I'm just glad to have found it now!

**Errors Not As Informative**
The errors in displayed by the pre-built functions do not give as much info as the run time ones.

E.g., I have a "sortOrder" property that should be set to either "asc" or "desc".  If I set this value to "" (empty string) in the run time version, it tells me:

> .views[0].sortOrder | should be equal to one of: "asc", "desc"

but in the pre-compiled version, the equivalent message is:
> .views[0].sortOrder | must be equal to one of the allowed values

Not so informative.

I think this one is because your `improveAjvError` function isn't getting the data that it needs to do it's thing.  These lines are failing:
```javascript
function improveAjvError(ajvErrorParam: any) {
  const ajvError = { ...ajvErrorParam };
  if (ajvError.keyword === 'enum' && Array.isArray(ajvError.schema)) {
    let enums = ajvError.schema;
```
because there is no `schema` property in the `ajvError`.   Here's what I get for `ajvError` in the pre-built validator functions:
```json
{
    "instancePath": "/views/0/sortOrder",
    "schemaPath": "#/definitions/CurrentSpaceSortOrder/enum",
    "keyword": "enum",
    "params": {
        "allowedValues": [
            "asc",
            "desc"
        ]
    },
    "message": "must be equal to one of the allowed values"
}
```
I get a  `schemaPath` property, but no `schema` property.

The good news is that all the info for an to get an informative error message is supplied there, so shouldn't be too much trouble to workaround this one.

**Comment by josdejong** [comment]
O wow, that is tricky. Yes indeed there is an `allErrors` flag that needs to be set to `true`. Looking in the docs I see that the AJV CLI has an option `--all-errors`, I suppose you're using that now. As for the improved error messages: yes that is indeed why I wrote `improveAjvError` in the first place:

The config that `svelte-jsoneditor` uses in `createAjvValidator` should give a good hint on what you need to configure when generating validator code upfront. So I guess you have to specify `--verbose` too to get the `schema` information.

https://github.com/josdejong/svelte-jsoneditor/blob/9d693f94ebeffa187a2f3ab8f85998b987be8b94/src/lib/plugins/validator/createAjvValidator.ts#L22-L27

**Comment by brownieboy** [comment]
@josdejong ,

Thank you, sir!

That  `verbose: true` flag was, indeed, what I was missing.

```javascript
const ajv = new Ajv({ allErrors: true, verbose: true, schemas: schemaDefsArray, code: { source: true } })
```

With that flag now in place, I'm getting a `schema` property in the `ajvError` variable, and my errors messages are making sense again.  😊

**Comment by josdejong** [comment]
💪
