### ISSUE TITLE
Cannot find module 'node-sass'

### ISSUE THREAD

**Issue by lalilaloe** [josdejong/svelte-jsoneditor#17]
Getting the following error after fresh install of svelte-kit. 

node v14.17.4
svelte v3.34.0
svelte-jsoneditor v0.1.6"

Might this be because it is missing in the dependencies

`[vite] Internal server error: Cannot find any of modules: sass,node-sass

Error: Cannot find module 'node-sass'
Require stack:
- /mnt/c/dev/repo/node_modules/svelte-preprocess/dist/modules/utils.js
- /mnt/c/dev/repo/node_modules/svelte-preprocess/dist/autoProcess.js
- /mnt/c/dev/repo/node_modules/svelte-preprocess/dist/index.js
  Plugin: vite-plugin-svelte
  File: /mnt/c/dev/repo/node_modules/svelte-jsoneditor/src/components/modals/SortModal.svelte`

**Comment by josdejong** [comment]
yeah, see docs: https://github.com/josdejong/svelte-jsoneditor#svelte-setup

I'm working on upgrading the setup to sveltekit. I hope this will make things a bit easier.
