### ISSUE TITLE
No possibility to edit empty arrays or objects

### ISSUE THREAD

**Issue by IegorShumov** [josdejong/svelte-jsoneditor#171]
![image](https://user-images.githubusercontent.com/68240508/197145087-b8e61312-0a00-4e83-bd56-892998ea0479.png)

**Comment by josdejong** [comment]
Thanks for your question Iegor. You can indeed not edit the value of an array like you can do with a number or string: it is not a value but it contains values. You can _insert_ new values in the array (and the same with an empty object):

![afbeelding](https://user-images.githubusercontent.com/568626/197146507-79ed5ed1-925f-4e2c-a99f-ab09556331c5.png)

**Comment by josdejong** [comment]
@IegorShumov I just implemented a `table` mode for the editor. In the table mode you can edit nested objects/arrays in a popup. I've now enabled opening this popup too from `tree` mode, which I think is exactly what you where looking for 😁 :

![afbeelding](https://user-images.githubusercontent.com/568626/206156145-77d5af04-7762-4a5d-b60b-0fcdea7f5d30.png)

**Comment by IegorShumov** [comment]
Thank you! It will be helpful 👍
