### ISSUE TITLE
Set selection and listen to selection changes?

### ISSUE THREAD

**Issue by sagIoTPower** [josdejong/svelte-jsoneditor#172]
Hi,

I would like to use the svelte-jsoneditor to create some mapping component. Mapping from a JSON source to JSON target format.
This can be seen on the screen shot below.
In order to migrate to this editor I look for two features:
1. highlight/select a element in the displayed JSON document, something like ```setSelection(path)```
2. register a callback if an element is selected in the editor: something like ```onSelection(path)```

The current mapper works as follows:
1. you select an element in the source document: pathSource
2. you select an element in the target document: pathTarget
3. this create a mapping

Is something like this possible with the current editor?
I have read the other issues and got the impression that for 1. there exists already a feature request #163.

Regards Christof

<img width="1728" alt="Generic_MQTT_MappingTemplate" src="https://user-images.githubusercontent.com/29702059/197349796-abe71728-c6b6-4d3b-b782-002ad05efd2c.png">

**Comment by josdejong** [comment]
Thanks for your inputs! Yes #163 is to discuss both getting and setting a selection. I've updated [my comment there](https://github.com/josdejong/svelte-jsoneditor/issues/163#issuecomment-1277397051) to clarify that a bit more. Let's continue the discussion there to keep it focused.
