### ISSUE TITLE
constructor options not working

### ISSUE THREAD

**Issue by stringa** [josdejong/svelte-jsoneditor#18]
Hello,

Working with the newest library, I've noticed some things....

navigationBar: false, mainMenuBar: false, readOnly: false, onClassName: CallbackFn(),

don't seem to be working.

**Comment by stringa** [comment]
just noticed that some of these may need to be under props={}, gonna test that

**Comment by stringa** [comment]
so, I am able to import the object, but I just import the JSONObject constructor. I am having trouble understanding how to do things like toggle readonly.

I've also noticed that when I enable mainMenuBar, the first time I click on a key on a long list, it's auto scrolls me to the top. very annoying for editing.

**Comment by josdejong** [comment]
I suppose you're using the plain JavaScript API, which looks like:

```js
const editor = new JSONEditor({
  target: document.getElementById('my-jsoneditor'),
  props: {
    ...
  }
})
```
This is all explained in the readme: https://github.com/josdejong/svelte-jsoneditor#api

> so, I am able to import the object, but I just import the JSONObject constructor. I am having trouble understanding how to do things like toggle readonly.

I haven't worked out an API for that for the plain JavaScript API. I created some methods like `editor.setMainMenuBar` (undocumented), but I'm not sure if that is the way to go. The Svelte component also exposes a method to update properties: `editor.$$set(props)`. I was thinking about creating a less scrary alias for that like `editorupdateProps`. Anyway, with this method you can update any property which is really simple and powerful: 

```js
editor.$$set({
  mainMenuBar: false,
  readOnly: true,
  // ...
})
```

> I've also noticed that when I enable mainMenuBar, the first time I click on a key on a long list, it's auto scrolls me to the top. very annoying for editing.

Can you open a separate issue about this and explain there how to reproduce this issue? (else this issue will get cluttered)

**Comment by josdejong** [comment]
The editor now exposes a method `updateProps` to change properties.

See docs: https://github.com/josdejong/svelte-jsoneditor#methods
