### ISSUE TITLE
Multiple IDs of caret svg's

### ISSUE THREAD

**Issue by Menkir** [josdejong/svelte-jsoneditor#187]
Hey guys,

i noticed that the caret svg's of a tree entry have the same ids.

In particular: 
`<svg version="1.1" class="fa-icon svelte-1dof0an" width="10" height="16" role="presentation" viewBox="0 0 320 512"><path id="path-0" d="M137.4 374.6c12.5 12.5 32.8 12.5 45.3 0l128-128c9.2-9.2 11.9-22.9 6.9-34.9s-16.6-19.8-29.6-19.8L32 192c-12.9 0-24.6 7.8-29.6 19.8s-2.2 25.7 6.9 34.9l128 128z"></path>  </svg>`

Actually, I don't mind as far as it works. However, my framework complains that ambiguous IDs are used. Also it doesn't matches the html spec for assigning ids. This could be a good first issue for beginners.

**Comment by josdejong** [comment]
This issue is fixed now in `v0.11.0` and later
