### ISSUE TITLE
Dark Theme - Highlighted section is not visible

### ISSUE THREAD

**Issue by spirostz** [josdejong/svelte-jsoneditor#188]
Hello,

There is a problem and the selected section is not highlighted in Dark Theme.
Below, on the left, we can see this missing highlighted section by comparing with the Light mode...

![image](https://user-images.githubusercontent.com/11974067/200805782-1f2817a2-e36a-40b9-b69e-ee5306a0bbb6.png)

**Comment by josdejong** [comment]
Thanks for reporting this bug, will fix it asap!

**Comment by josdejong** [comment]
This issue is fixed now in `svelte-jsoneditor@0.10.0` and https://jsoneditoronline.org v6.9.4 (you may need to refresh your browser with F5 or Ctrl+F5).
