### ISSUE TITLE
Missing package-vanilla/index.js

### ISSUE THREAD

**Issue by avoutsas67** [josdejong/svelte-jsoneditor#194]
Hello 

I have tried to use the browser examples for vanilla Javascript and the basic_usage.html example is missing the package-vanilla/index.js file - line 23.
import { JSONEditor } from '../../package-vanilla/index.js'

Can you please include the file or advise how to generate it? 

Thanks
Achilleas

**Comment by josdejong** [comment]
If you check out the source code repository, you'll have to first build the bundle before you can use it. To do that, run:

``` 
npm install
npm run build
```

**Comment by josdejong** [comment]
Alternatively, you can replace the url with a CDN, like:

```js
import { JSONEditor } from 'https://cdn.jsdelivr.net/npm/vanilla-jsoneditor@0.10.1/index.js'
```
