### ISSUE TITLE
custom edit menu

### ISSUE THREAD

**Issue by Reload0213** [josdejong/svelte-jsoneditor#197]
<img width="283" alt="스크린샷 2022-11-25 오후 7 48 32" src="https://user-images.githubusercontent.com/85751554/203967925-983fbed9-0f6a-4cb4-980a-9fbf9c05cffd.png">

I have a question for the first time in a while. Do you support customizing the edit buttons in the picture above?

**Comment by josdejong** [comment]
That is not yet supported, but it is on the wish list: #82
