### ISSUE TITLE
schema validation is not working on https://jsoneditoronline.org/

### ISSUE THREAD

**Issue by m1r4c** [josdejong/svelte-jsoneditor#198]
Hello,

Thank you for your incredible work with jsoneditor, much appreciated :)

Was just about to validate a schema on https://jsoneditoronline.org/ but looks like it needs an update to work with newer version of svelte-jsoneditor?
Getting this message when I try to use a schema in the right panel and set it as validation source:
![2022-11-30_08h15_43](https://user-images.githubusercontent.com/12200804/204731754-b35e0a93-a099-4479-a8c5-788daa5be083.png)

BR
Lars

**Comment by josdejong** [comment]
Ouch! That is an ugly bug. Thanks for reporting @m1r4c . 

This regression was introduced about two weeks ago in v6.9.4 after upgrading to the latest `svelte-jsoneditor`, and indeed is missing a small adjustment. I've fixed it now in v6.9.7. You may need to refresh your browser with F5 or Ctrl+F5 (you can find the current version under Help > About).
