### ISSUE TITLE
NextJs - vanilla-jsoneditor - server side error render

### ISSUE THREAD

**Issue by qbacuber** [josdejong/svelte-jsoneditor#207]
Hi, I encountered a problem while building my NEXTjs application, the page where the JSON editor is located does not display. 
On the DEV environment everything works, there are no errors. 

Site gets error 304 -but user redirects to 404 page
![image](https://user-images.githubusercontent.com/38834474/207890369-e8d988b7-3047-4a9c-b368-9be7ce298d41.png)

The console shows this error
![image](https://user-images.githubusercontent.com/38834474/207890447-1320b4cf-2422-4463-a17b-1dc8bf8e3545.png)

Main Packages: 
- "vanilla-jsoneditor": "0.11.4",
- "next": "^13.0.6",
- "react": "^18.2.0",

File with Editor:
```ts
import { JSONEditor, JSONEditorPropsOptional } from "vanilla-jsoneditor";
import { useEffect, useRef } from "react";

export function CustomJSONEditor(props: JSONEditorPropsOptional) {
  const refContainer = useRef<HTMLDivElement | null>(null);
  const refEditor = useRef<JSONEditor | null>(null);

  useEffect(() => {
    // create editor
    if (typeof window !== "undefined" && typeof document !== "undefined") {
      if (refContainer.current !== null) {
        refEditor.current = new JSONEditor({
          target: refContainer.current,
          props: {},
        });
      }

      return () => {
        // destroy editor
        if (refEditor.current !== null) {
          refEditor.current.destroy();
          refEditor.current = null;
        }
      };
    }
  }, []);

  useEffect(() => {
    if (refEditor.current) {
      refEditor.current.updateProps(props);
    }
  }, [props]);

  return typeof window !== "undefined" && typeof document !== "undefined" ? (
    <div ref={refContainer} />
  ) : (
    <>Some text </>
  );
}
```

File using the Editor: 
```ts
import dynamic from "next/dynamic";
import { useState } from "react";

const Editor = dynamic(
  () => import("ui/common/components/JSONEditor/JSONEditor").then((_) => _.CustomJSONEditor),
  {
    ssr: false,
  },
);
export default function JsonEditorTest() {
  const [showEditor, setShowEditor] = useState(true);
  const [readOnly, setReadOnly] = useState(false);
  const [content, setContent] = useState({
    json: {
      greeting: "Hello World",
      ok: true,
      values: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
    },
    text: undefined,
  });

  return (
    <div className="">
      <p>
        <label>
          <input type="checkbox" checked={showEditor} onChange={() => setShowEditor(!showEditor)} />
          Show JSON editor
        </label>
      </p>
      <p>
        <label>
          <input type="checkbox" checked={readOnly} onChange={() => setReadOnly(!readOnly)} /> Read
          only
        </label>
      </p>

      {showEditor && (
        <>
          <h2>Editor</h2>
          <div className="my-editor">
            {typeof window !== "undefined" && typeof document !== "undefined" && (
              //@ts-ignore
              <Editor content={content} readOnly={readOnly} onChange={setContent} />
            )}
          </div>
        </>
      )}

      <>
        <h2>Contents</h2>
        <pre>
          <code>{JSON.stringify(content, null, 2)}</code>
        </pre>
      </>
    </div>
  );
}
```

**Comment by josdejong** [comment]
Thanks for reporting Jakub. 

Does the issue occur too in a CodeSandbox? I.e. in a React application without NextJS? Can you also verify whether `props` has indeed proper contents when passing it to `refEditor.current.updateProps(props);`, for example with a `console.log('props', props)`?

I suppose you've seen this example CodeSandbox: https://codesandbox.io/s/svelte-jsoneditor-react-59wxz

**Comment by qbacuber** [comment]
Hey, NextJS version 13 still has a bunch of bugs, I will wait until the stable version comes out and then check again if JSONeditor works on it.
It's probably a server side rendering problem. Here the errors I have yet managed to encounter on another browser:
<img width="1124" alt="Zrzut ekranu 2022-12-17 o 09 53 26" src="https://user-images.githubusercontent.com/38834474/208234661-3b28e23d-9da7-451e-aaf2-7a12b7c04851.png">

As for my project, I did a downgrade  NEXTjs to version 12 and everything works, no problems.

**Comment by josdejong** [comment]
🤔 OK clear, lets assume this is related to a bug in nextjs 13. I'll close this issue then.
