### ISSUE TITLE
Issue with Use in NextJs

### ISSUE THREAD

**Issue by tylerjlawson** [josdejong/svelte-jsoneditor#22]
I realize this package does not necessarily support the build process of NextJs, but I wanted to share the error I am getting with the module for `JSONEditor` in `svelte-jsoneditor/dist/jsoneditor.js` that is crashing my dev server.

```ts
import { JSONEditor } from 'svelte-jsoneditor/dist/jsoneditor.js';
```

```
TypeError: Cannot read properties of undefined (reading 'ace')
    at file:///Users/.../node_modules/svelte-jsoneditor/dist/jsoneditor.js:47:20281
    at file:///Users/.../node_modules/svelte-jsoneditor/dist/jsoneditor.js:47:20475
    at file:///.../node_modules/svelte-jsoneditor/dist/jsoneditor.js:47:20483
    at file:///Users/.../node_modules/svelte-jsoneditor/dist/jsoneditor.js:47:383518
    at ModuleJob.run (node:internal/modules/esm/module_job:183:25)
    at async Loader.import (node:internal/modules/esm/loader:178:24)
    at async importModuleDynamicallyWrapper (node:internal/vm/module:437:15)
ERROR: "dev:next" exited with 1.
```

I am not sure what ace is in this case, but would appreciate any ideas for debugging.  

Sidenote: I updated the react codesandbox in a fork to match the new interface for content - https://codesandbox.io/s/svelte-jsoneditor-react-forked-0k1bl

**Comment by tylerjlawson** [comment]
This issue can be ignored - It was resolved by deleting my `.next` directory and rerunning `npm run dev`

Still would appreciate the react codesandbox being updated as described above though

**Comment by tylerjlawson** [comment]
Wondering if this might be related somehow? https://github.com/ajaxorg/ace-builds/issues/129

**Comment by tylerjlawson** [comment]
Wondering if this issue: https://github.com/json-editor/json-editor/issues/1025 could be addressed in this project?

**Comment by tylerjlawson** [comment]
So I figured out from the ace-builds thread above that adding 
```ts
import 'ace-builds';
import 'ace-builds/webpack-resolver';
```
fixes this issue, but this seems less than ideal

**Comment by josdejong** [comment]
Thanks for sharing your workaround 👍

**Comment by josdejong** [comment]
I'll close this issue now. Ace has been replaced with Code Mirror, this probably solves this issue. If not, please reopen this issue or create a new one.
