### ISSUE TITLE
Classic view editor

### ISSUE THREAD

**Issue by wongshung** [josdejong/svelte-jsoneditor#220]
I found that class view editor is disabled. Any way to use that? I still think that editor  is more simple  and easy to use.

**Comment by josdejong** [comment]
Thanks for your feedback Leepi. I removed a link from the "about" section referring to the classic version, but the classic version is still available for anyone who likes it better: 

https://jsoneditoronline.org/classic/index.html

Can you explain a few concrete things that you find easier to do in the classic version? Like edit a value or insert a new field?

**Comment by wongshung** [comment]
> https://jsoneditoronline.org/classic/index.html

Most of the time, I just want to view and check the json content. I don't need to edit, or do some complicated editting work for the json. In that case, it is more convenient to just use a simple or easy to read editor.

**Comment by josdejong** [comment]
Ok clear. Your feedback is very valuable, there may be something simple missing in the new editor that would be easy to fix.

So, why does the new editor feel more complex to view your JSON data? Do you find the user interface more cluttered, or do you find it harder to get your document opened in the editor? Also: do you use the text mode or tree mode for viewing?

**Comment by XueMeijing** [comment]
Hi,
In text mode, I found that the successor editor  will expand empty ```{}`` or ```[]``` and seems that there have no params to config it. it occupy more lines and looks not intuitively.

![image](https://user-images.githubusercontent.com/35559153/218692381-062441a9-2271-46e2-b45d-ca3162e6a8d3.png)

besides, when expand an object, the classic editor gray vertical line disappleared, would it be better to recover the gray vertical line ? It's harder to find the end point， especially if a long object overflow the editor container 

![image](https://user-images.githubusercontent.com/35559153/218695997-46a036e1-f874-4770-aae5-d780b0dd38e2.png)

**Comment by josdejong** [comment]
Thanks for reporting @XueMeijing, this is a bug in the `format` function. I will look into it.

**Comment by josdejong** [comment]
The formatting issue has been fixed now in `svelte-jsoneditor@0.14.5` and https://jsoneditoronline.org `v6.12.4`.

I'll now close this issue as there are no other actionable requests. More feedback is very welcome though!
