### ISSUE TITLE
JSONC (JSON with Comments) Support

### ISSUE THREAD

**Issue by Sinjai** [josdejong/svelte-jsoneditor#222]
Is there a possibility for support for JSON with Comments, like the `jsonc` "language" in VSCode? 

Or a recommendation for another library which can do this (even if otherwise less feature-rich)?

**Comment by josdejong** [comment]
Duplicate of #157, let's continue the discussion there.

**Comment by Sinjai** [comment]
Thanks, didn't know JSON5 is (includes?) JSONC.
