### ISSUE TITLE
styles about vertical gray line when expand objects in text mode

### ISSUE THREAD

**Issue by XueMeijing** [josdejong/svelte-jsoneditor#225]
thanks for ur great work about format in #220, but maybe the second issue you did't noticed about. It's about object vertical gray line, in classic code mode  which appeared as ```ace_indent-guide``` element ,  but it seems that there have only text-indent but  not vertical gray line in successor. As i said  It's harder to find the end point without the vertical gray line，especially if a long object overflow the editor container.

![image](https://user-images.githubusercontent.com/35559153/219244933-0077c6b9-802a-4633-b896-6a71c93f26fd.png)

**Comment by josdejong** [comment]
Ah sorry, I indeed forgot about that. Fixed via 09f257568567eb1b01ff68b955d69bebe54cff95 (not yet published)

**Comment by josdejong** [comment]
Published now in `v0.14.6`
