### ISSUE TITLE
Add field to easily check error in onChangeStatus

### ISSUE THREAD

**Issue by kloon15** [josdejong/svelte-jsoneditor#226]
Right now if i need to check if the JSON is valid i have to write a long ass sentence:
```
const valid = ((status.contentErrors as ContentParseError).parseError ||
                            (status.contentErrors as ContentValidationErrors).validationErrors?.length)
                            ? false : true
```

I would like to have a field to easily check for error and its type:
```
errorType: "validation" | "parse" | "none"
```

Thank you.

**Comment by josdejong** [comment]
We could expose the two internal functions (typeguards) `isContentParseError` and `isContentValidationErrors`, would that address your issue?

Code: https://github.com/josdejong/svelte-jsoneditor/blob/main/src/lib/typeguards.ts#L72-L86

**Comment by kloon15** [comment]
That also works for me.

**Comment by josdejong** [comment]
👍

**Comment by josdejong** [comment]
The just published `v0.14.10` now exports `isContentParseError` and `isContentValidationErrors`.

**Comment by kloon15** [comment]
isContentValidationErrors returns true falsely for a valid document:
```
Errors: Object { validationErrors: [] }[create.tsx:100:36]
isContentValidationErrors: true [create.tsx:101:36]
```

**Comment by josdejong** [comment]
These two functions are typeguards, they only check the type.

Depending on your exact needs you can do something like:

```js
function getContentErrorsType(contentErrors: ContentErrors) : 'parse' | 'validation' | 'none'  {
  return isContentParseError(contentErrors)
    ? 'parse'
    : isContentValidationErrors(contentErrors) && contentErrors.validationErrors.length > 0
    ? 'validation'
    : 'none'
}
```

**Comment by josdejong** [comment]
Thinking about it, I think the editor should not return an empty `contentErrors : { validationErrors: [] }` in case of a valid document, but `null` in that case. Then your check simplifies to `contentErrors === null`.

**Comment by kloon15** [comment]
> Thinking about it, I think the editor should not return an empty `contentErrors : { validationErrors: [] }` in case of a valid document, but `null` in that case. Then your check simplifies to `contentErrors === null`.

Yea that would be the optimal solution.

**Comment by josdejong** [comment]
👍 I'll implement that

**Comment by josdejong** [comment]
Published now in `v0.15.0`. Can you give it a try @kloon15?

**Comment by kloon15** [comment]
Sure ill test it.

**Comment by kloon15** [comment]
Works as expected, thank you!

**Comment by josdejong** [comment]
Thanks for the feedback and for helping make the library a bit better 😄

**Comment by kloon15** [comment]
My pleasure, now i just need to figure out how to deal with Date objects in it.

**Comment by josdejong** [comment]
> now i just need to figure out how to deal with Date objects in it

You can configure your own JSON parser with the `parser` option, so you can provide a JSON parser where you revive and stringify Dates.
