### ISSUE TITLE
Line numbers are rendered incorrectly

### ISSUE THREAD

**Issue by EnigmaJJ** [josdejong/svelte-jsoneditor#234]
Hi, I used vanilla-jsoneditor in React. I found line numbers are rendered incorrectly when the editor was rendered firstly, and once the editor has the focus, line numbers are rendered correctly.
I try to use refresh when I set content, but it doesn't help.

![image](https://user-images.githubusercontent.com/39852187/222079756-20eb351c-a811-49f1-b81e-5124da917bc9.png)

**Comment by josdejong** [comment]
Can it be that your editor is first rendered inside a div with height 0, or a div that is not yet attached to the dom, or with a different font size or so? Best would be to figure out the cause of that and initialize the editor right in one go. Alternatively, you can force the editor to re-render by calling `jsoneditor.refresh()`.

**Comment by EnigmaJJ** [comment]
Thanks for your reply.


I guess it may be related to the initialization order of components, because sometimes it was rendered as follows:
![image](https://user-images.githubusercontent.com/39852187/222092236-fe61cdbd-204e-4213-b49a-97ef9f172193.png)


The editor was used in the Modal of antd, and I created the editor in the componentDidMount.
But like I mentioned, I try to call refresh when I set content, but it doesn't help, it is strange. :(

**Comment by josdejong** [comment]
Is it possible to to create a minimal example demonstrating the issue?

**Comment by josdejong** [comment]
I see the model you use from Ant Design uses animation when opening the modal, changing the size or zoom level or so from 0 to the actual size in something like 200ms. You have to call `.refresh()` after the animation is finished. Or alternatively, disable the animation. Ideal would be if the modal has a callback when animation finished but I didn't see that.

**Comment by EnigmaJJ** [comment]
I understand, thank you for your patient reply :)
