### ISSUE TITLE
Updating empty content returns parseError until edited manually

### ISSUE THREAD

**Issue by kloon15** [josdejong/svelte-jsoneditor#237]
I'm implementing an upload feature and i'm having the issue of 2 things that must be related:

1. Update `JSONEditor` with a content of `{ text: "" }`, and it returns `unexpected end of data at line 1 column 1` in `OnChangeStatus` (this is understandable, its not a JSON indeed).
2. Pasting a valid JSON to the editor will not clear the above `parseError`, only by manually editing.

This only happens with the empty content strangely.

![image](https://user-images.githubusercontent.com/1431170/223152253-eea04bdb-3082-49f8-8be6-64ea8fa7550d.png)

**Comment by josdejong** [comment]
Thanks for reporting these bugs @kloon15

**Comment by josdejong** [comment]
Fixed in `v0.16.0`
