### ISSUE TITLE
Incomplete/Missing documentation 

### ISSUE THREAD

**Issue by farafalil** [josdejong/svelte-jsoneditor#239]
The in-depth documentation page for title [Beautify](https://jsoneditoronline.org/indepth/beautify/beautify-json/) looks incomplete. Only ended with a mini editor.

**Comment by josdejong** [comment]
Thanks for taking the time to report this issue, well spotted! It turned out that mini editor caused an issue making the actual contents of the article below the editor not to be rendered. This is fixed now (you may need to refresh the page).
