### ISSUE TITLE
Copy compacted returns undefined when pasting anywhere

### ISSUE THREAD

**Issue by delkov2007** [josdejong/svelte-jsoneditor#241]
Copy Compacted produce undefined result when pasting it anywhere
[Feedback _ JSON Editor Online.webm](https://user-images.githubusercontent.com/10463128/226924524-e239835f-c08d-40aa-97ee-14666dc5f02e.webm)

**Comment by josdejong** [comment]
Thanks for reporting @delkov2007, I see indeed the copy document button is broken. Will fix it asap.

**Comment by josdejong** [comment]
This has been fixed now in https://jsoneditoronline.org `v6.13.1`. You may need to refresh your browser.
