### ISSUE TITLE
Accept POST request for larger JSON

### ISSUE THREAD

**Issue by black-inc-service** [josdejong/svelte-jsoneditor#242]
For the online formatter it can accept JSON in the URL query as shown in the documentation
https://jsoneditoronline.org/#left=json.ENCODED_JSON_CONTENTS&right=json.ENCODED_JSON_CONTENT
This has a limitation of only small JSON objects due to the max URL size.
Is it possible to implement a POST method where you can add left and right as part of the body to format larger JSON?

**Comment by josdejong** [comment]
Maybe something like https://keyvalue.immanuel.co/? Found that when googling for "online key value store".

**Comment by black-inc-service** [comment]
Good find, I think this could work.
