### ISSUE TITLE
Donate options are blocked

### ISSUE THREAD

**Issue by sengiv** [josdejong/svelte-jsoneditor#243]
Great site!
Not sure if this belongs here, pls delete issue if irrelevant.
Your Paypal donate options is limited only to the States, i think.
You're probably loosing donation because of this,
I recommend use Ko-Fi or Patreon
![image](https://user-images.githubusercontent.com/43817262/228706641-97ad046f-1c59-4964-aaee-6ac4a8f193a6.png)

**Comment by josdejong** [comment]
Thanks for bringing this up Sengiv. And for pressing the donate button figuring this out in the first place ;) 

I'll look into whether lack of Paypal support is an issue in many countries or not. And I'll have a look into Patreon next week. Setting it up will take some time though.

It is also possible to donate via Github Sponsors: https://github.com/sponsors/josdejong
