### ISSUE TITLE
Hide contextmenu in tree mode

### ISSUE THREAD

**Issue by qishibo** [josdejong/svelte-jsoneditor#25]
I just want a pure editable Json tree view, so can I hide context menu besides css?

I want to hide both drop-down triangle and insert triangle, like this
![image](https://user-images.githubusercontent.com/5136418/137588155-e3cbff2e-16a2-4733-99b6-39a199ad71bc.png)

**Comment by qishibo** [comment]
And if I use 'tree' mode, for reducing additional libs, can I drop ace editor like jsoneditor.min.js?

**Comment by qishibo** [comment]
very strange, if the first element `{` was in view, everything goes well, but if `{` scrolls out of view, 'auto scroll' happens.

**Comment by josdejong** [comment]
The scroll into view of the editor only works when it's contents part is scrolling, not when the whole editor is scrolling: the anchor element on which the scroll is applied is part of the editor itself.

**Comment by josdejong** [comment]
I'll close this issue now, please reopen if needed.
