### ISSUE TITLE
Implement search in text mode when read only

### ISSUE THREAD

**Issue by crystalrain125** [josdejong/svelte-jsoneditor#251]
Could we provide search functionality to text mode when in read-only mode? It's currently supported in tree mode.

<img width="415" alt="Screenshot 2023-04-05 at 4 49 18 PM" src="https://user-images.githubusercontent.com/27582787/230238221-c2e0d6c2-1e86-403b-93fb-a6ace3e4179e.png">

**Comment by josdejong** [comment]
Good idea, thanks for your suggestion!

Anyone interested in implementing support for search (not replace) in text mode when read only?

**Comment by laneparton** [comment]
@josdejong This is something I'm interested in for our application. I was experimenting a little bit with the repo - this is my first time actually looking at the underlying package, codemirror.

I'm sure you've got plenty of experience with codemirror 😄, do you think we could achieve this with the `editable` + `readOnly` options?

I see the comments from this PR: https://github.com/josdejong/svelte-jsoneditor/pull/130

Maybe we need to specifically handle mobile, but open up editable as an option? What are your thoughts or how would you advise moving forward?

**Comment by josdejong** [comment]
Thanks for your offer Lane.

I looked into it, and it was mainly caused by #142. I fixed #142 now and made sure the search button is displayed in readOnly mode (https://github.com/josdejong/svelte-jsoneditor/commit/50f8889597466ec8027c07dda3d4e613684aa9dc).
