### ISSUE TITLE
Is there a way to disable debug messages?

### ISSUE THREAD

**Issue by KiranMurthy-Au** [josdejong/svelte-jsoneditor#253]
I see this in browser console window. Is there a way to disable debug messages?
<img width="760" alt="Screenshot 2023-04-13 at 5 35 26 AM" src="https://user-images.githubusercontent.com/114429278/231760120-78e350a3-b106-4c01-9b31-b4ebe2c0700c.png">

**Comment by josdejong** [comment]
Yes, to turn on debugging output, enter the following in your browsers JavaScript console:

```
localStorage.debug="*"
```

Then reload the page.

To turn off debugging output, enter the following in your browsers JavaScript console:

```
delete localStorage.debug
```

Then reload the page.
