### ISSUE TITLE
It is possible to use ajv-i18n in the editor? 

### ISSUE THREAD

**Issue by jakub-mar** [josdejong/svelte-jsoneditor#254]
I am thinking, is it possible to use ajv-i18n to translate the ajv validation messages in the editor, or is it possible to translate the ajv messages in any other way?

**Comment by josdejong** [comment]
Yes, you can provide your own `validator`, and you can configure provided `createAjvValidator` as you like using the `onCreateAjv` parameter. 

Looking at https://ajv.js.org/packages/ajv-i18n.html it requires calling a localization function on validation errors, so I guess it is easiest to write a wrapper function around `createAjvValidator` that first gets the validation errors, then apply localization, and then return them.
