### ISSUE TITLE
Where is dist folder for javascript use

### ISSUE THREAD

**Issue by hoogw** [josdejong/svelte-jsoneditor#265]
I want to use it in browser with plain javascript. 
But after I download .zip, can't find dist folder.

I don't know how to build to generate this file.

 /node_modules/svelte-jsoneditor/dist/jsoneditor.js 

Can you include dist folder in release .zip file or show us how to bundle it to generate a dist folder?

This is error when I try to build dist folder,

<img width="605" alt="Screenshot 2023-04-29 at 10 20 58 AM" src="https://user-images.githubusercontent.com/419582/235315631-0590760c-a0be-4589-815b-850bb6e570ad.png">

I also tried 
 ```
// svelte-jsoneditor (vanilla-jsoneditor for plain js)
   <script src='/public/utility/vanilla-jsoneditor/index.js'>
```
does not work either

I tried 53, but doesn't make it work for me
#https://github.com/josdejong/svelte-jsoneditor/issues/53

try #https://github.com/josdejong/svelte-jsoneditor/issues/165
still not work,

How to make it works?

**Comment by josdejong** [comment]
I think you're looking for the vanilla bundle. This bundle is an ES module though, not UMD, see #165, #195.

Docs: https://github.com/josdejong/svelte-jsoneditor#standalone-bundle-use-in-react-vue-angular-plain-javascript-

**Comment by hoogw** [comment]
I did a test page, but it does not work, I can't see it. However, it load ok, I don't see error in console. 

Here is code, 
<img width="1368" alt="Screenshot 2023-05-03 at 4 06 37 PM" src="https://user-images.githubusercontent.com/419582/236069651-5fd1dfcc-f7d5-466f-92a7-670e5f7f888e.png">


Here is f
<img width="718" alt="Screenshot 2023-05-03 at 4 08 20 PM" src="https://user-images.githubusercontent.com/419582/236070415-3de83665-98e6-491b-9017-d980d277e91b.png">
older

**Comment by josdejong** [comment]
Do you get the source mapping in the following example? https://jsbin.com/yuwapaj/edit?html,output 

![afbeelding](https://user-images.githubusercontent.com/568626/236153145-2a16b84e-2d67-4206-8934-a291c0922b08.png)

**Comment by hoogw** [comment]
Thank you,  [josdejong](https://github.com/josdejong) that solution is perfect !!
I closed this ticket. 


This is how I use new vanilla jsoneditor, click link

[https://transparentgov.net/json2tree/esri/server/folder.html?org=https%3A%2F%2Fgisportal.hrsa.gov%2Fserver%2Frest%2Fservices&url=https%3A%2F%2Fgisportal.hrsa.gov%2Fserver%2Frest%2Fservices&select_folder=74&select_layer=1](https://transparentgov.net/json2tree/esri/server/folder.html?org=https%3A%2F%2Fgisportal.hrsa.gov%2Fserver%2Frest%2Fservices&url=https%3A%2F%2Fgisportal.hrsa.gov%2Fserver%2Frest%2Fservices&select_folder=74&select_layer=1)
![Screenshot 2023-05-11 at 12 22 46 PM](https://github.com/josdejong/svelte-jsoneditor/assets/419582/007d5a1f-a489-40bf-b75c-f78cdf95ef66)
