### ISSUE TITLE
expand all fields in tree mode in ReactJS

### ISSUE THREAD

**Issue by nitzcard** [josdejong/svelte-jsoneditor#266]
Hi, I try to expend all the fields in tree mode in react right from the start, 
I saw there is an expand function:
`refEditor.current?.expand((path) => true);`

I try to do it in the useEffect when initting the library but it doesn't work, 
do you have an idea how it can be achieved?

**Comment by nitzcard** [comment]
https://github.com/josdejong/svelte-jsoneditor/pull/267

**Comment by josdejong** [comment]
Thanks for your PR @nitzcard . I'm not entirely sure I understand the original issue: at the start, the document contents _is_ expanded by default. See for example this basic React example: https://codesandbox.io/s/svelte-jsoneditor-react-59wxz

**Comment by nitzcard** [comment]
At my internal system it doesn't start expanded all the times,
I think it has to do with getDefaultExpand()

**Comment by josdejong** [comment]
Can you share a minimal example demonstrating your issue?

The only case where I know it happens is if you initially load an empty document, and later _update_ it with actual contents. The editor leaves the expanded state as is when updating a document. When I load a new document, I normally create a new editor with clean state, so it expands the document contents like it should.

**Comment by nitzcard** [comment]
Could be that's what happens at my form infra internally, when the data loads after. What do u suggest?

**Comment by josdejong** [comment]
> If that is the case, how can I enforce expanded at the first time the actual data loads?

Either create a new editor with the document, or use `.set(...)` initially instead of `.update(...)`.

**Comment by nitzcard** [comment]
I use `updateProps` as you wrote in your react demo to load the content, as I can't load it initially. 
To my understanding it doesn't creates a new editor so why it breaks the expanded state? 
This is a workaround, but it still not works 100% of the time: 
![image](https://user-images.githubusercontent.com/123297447/235626776-e3e881f8-f12b-4fda-b9f3-bb79ee705dcf.png)

can you help to think of a solution?

**Comment by josdejong** [comment]
I think what should work is:

- do _not_ pass `content` via `refEditor.current.updateProps`, remove it from the props before passing
- when loading the document initially, use `refEditor.current.set(content)` (that will reset the state of the editor)
- when loading the document consecutively, use `refEditor.current.update(content)` (that will keep the state of the editor)

Alternatively, you can create the editor only after you have the document and can directly pass it during initialization of the editor.

**Comment by nitzcard** [comment]
Waiting for the editor to load when the content loads is not doable for me, because sometimes there is no content and I would not know that (and I want the instruction message when text: ''), so I need a different solution. 
I think giving the control about expand/collapse is good, what if user wants the documents to starts collapsed/expanded regardless the content?

**Comment by josdejong** [comment]
One way or another, you will need to tell the editor when to keep the expanded state or reset it. Only you know the difference between loading a new document versus updating the existing document. The `startExpanded` option in the PR you propose does not solve that issue. What could be useful is introducing an option `expand`, but that would still not address your issue. 

You will need to let the editor know when to reset the state of the editor by either (1) creating a new editor, (2) use the method `.set()` instead of `.update()`, or (3) invoke the method `.expand()` after loading your document. I think the current API is sufficient for that.

On a side note: I was thinking that maybe your code in https://github.com/josdejong/svelte-jsoneditor/issues/266#issuecomment-1531148769 does not work because you call `.expand` without awaiting `updateProps` to rerender the app, you would have to call it like:

```js
await refEditor.current.updateProps(props)
//...
if (...) {
  await refEditor.current.expand(...)
}
```

**Comment by josdejong** [comment]
Good to mention here: we're thinking about exposing the internal state of the editor so you can control that via props, see https://github.com/josdejong/svelte-jsoneditor/issues/163#issuecomment-1465892695. That would introduce another option to change/reset the expanded state whenever you want.

**Comment by nitzcard** [comment]
using await inside useEffect is discouraged, but it's not working.
I think my only solution rn is to use "set" on initial content loading, 
I'll update if works good :)

**Comment by nitzcard** [comment]
ok so I implementing it for me via set is still very hacky with a lot of edge cases, 
I would still be glad for an option to enforce the state of the editor to be expanded even without content.

**Comment by josdejong** [comment]
I'm still not sure  whether I correctly understand what you're trying to do. 

Can you create a minimal CodeSandbox example demonstrating the issue? Can be based on https://codesandbox.io/s/svelte-jsoneditor-react-59wxz

**Comment by josdejong** [comment]
Any more information on this @nitzcard ? If not relevant anymore I'll close this issue.
