### ISSUE TITLE
Do not throw a wrong format error

### ISSUE THREAD

**Issue by Hikaru67** [josdejong/svelte-jsoneditor#268]
If a attribute have empty value like that `{ "lt": "nginx", "url":, "cl": 123 }`, the attribute "url" will be removed and formatted normally instead of throwing error and pointing where is the problem. I think it should be a better if throw error in this case.

**Comment by josdejong** [comment]
Thanks for reporting, the parser should indeed throw an error in case of a missing value. (an empty value can be represented using `null`)

**Comment by josdejong** [comment]
See https://github.com/josdejong/lossless-json/issues/247

**Comment by josdejong** [comment]
This has been fixed now in the `lossless-json` library, and in the web application https://jsoneditoronline.org.
