### ISSUE TITLE
Is it possible to have comments inline?

### ISSUE THREAD

**Issue by pkrall520** [josdejong/svelte-jsoneditor#269]
Is it possible to allow for comments in the json editor? something like 
![image](https://user-images.githubusercontent.com/8525633/236942309-6bb57a68-1d9e-44f2-bc07-17c99deec726.png)

**Comment by josdejong** [comment]
The editor only supports JSON, which does not support comments. 

There is a discussion though about implementing for example JSON5 support which does have comments, see #157
