### ISSUE TITLE
"Failed to resolve import from ajv" error

### ISSUE THREAD

**Issue by Metehan-Altuntekin** [josdejong/svelte-jsoneditor#271]
I am getting this error when I try to use it in a Svelte workspace in a monorepo:

"Failed to resolve import "ajv/dist/runtime/validation_error" from "node_modules\.vite\deps\svelte-jsoneditor.js?v=dab92afd". Does the file exist?"

![image](https://github.com/josdejong/svelte-jsoneditor/assets/86600423/08789dea-e6ad-4723-beec-540b0828d208)

When I check `node_modules`, ajv appears to be not installed:
![image](https://github.com/josdejong/svelte-jsoneditor/assets/86600423/a0b674a2-5458-42d6-aa34-e0c83dcf4012)

When I add ajv as a dependency to the workspace, it appears in the `node_modules`  error goes away. 

---

System: Windows 10 Pro
Node: 18.13.0
PNPM: 8.1.1

Project: https://github.com/cozemble/monorepo
Workspace: https://github.com/cozemble/monorepo/tree/main/frontend/datatable

**Comment by josdejong** [comment]
The `package.json` of the npm library `svelte-jsoneditor` does contain `ajv` in the dependencies. I do not understand why any client would not install the dependency? Can you provide a minimal example demonstrating the issue?

See package.json: https://unpkg.com/svelte-jsoneditor@0.17.3/package.json

**Comment by Metehan-Altuntekin** [comment]
Yeah, that is really weird isn't it? I think it's related to `pnpm` more than `svelte-jsoneditor` itself. Even when it is not a monorepo, `ajv` is not installed properly when I use `pnpm` but `npm` or `yarn` installs just right.

_Example of installing with `pnpm` in a non monorepo poject:_

![image](https://github.com/josdejong/svelte-jsoneditor/assets/86600423/666504dc-9964-46f0-ab8c-14e9ebe759e6)
---

_Example of installing with `npm` in a non monorepo project:_

![image](https://github.com/josdejong/svelte-jsoneditor/assets/86600423/0a1520d8-684f-4631-9dbf-be8325a6ff07)

**Comment by Metehan-Altuntekin** [comment]
Found more details, apparently `pnpm` installs package dependencies into `node_modules/.pnpm/` directory like so:

![image](https://github.com/josdejong/svelte-jsoneditor/assets/86600423/ea614338-5c9c-4241-ab71-de917d2dac9b)

The non-monorepo `pnpm` installed repository works just fine. But the error occurs in the monorepo one even though it installs `ajv` to that directory too:

![image](https://github.com/josdejong/svelte-jsoneditor/assets/86600423/2fd1303a-4dd6-47f4-8811-c8c55c6a0d0b)

But in a monorepo, `ajv` is installed in the `node_modules/.pnpm/` directory of the repo root. Not in the workspace's `node_modules/.pnpm` of the nested workspace. This behaviour is not exceptional for `ajv` or `svelte-jsoneditor` though, it appears to be the way of doing things for `pnpm`.

**Comment by josdejong** [comment]
Maybe this topic is relevant: https://stackoverflow.com/questions/70597494/pnpm-does-not-resolve-dependencies

**Comment by Metehan-Altuntekin** [comment]
Thanks @josdejong, it helped but the trade-off is that it allows to import non declared dependencies and that is not ideal. I found that enabling that only for `ajv`  with `public-hoist-pattern[]=ajv` also works and it's less dangerous. Still, it will not prevent importing `ajv` in workspaces that doesn't have it as a dependency so not finding it ideal.

I think the issue may be more closely related to Vite, since this error occurs within a [Vite Dependency Pre-Bundling](https://vitejs.dev/guide/dep-pre-bundling.html#caching).

I have checked the same file at 2 different cases and there are differences in way it imports `ajv`

When I install with `pnpm i`:

![image](https://github.com/josdejong/svelte-jsoneditor/assets/86600423/2f617f38-cd78-4f15-b0cc-2271a34b54df)

When I install with `pnpm i --shamefully-hoist=true`:

![image](https://github.com/josdejong/svelte-jsoneditor/assets/86600423/4507be40-644a-4e0c-b359-f4467d688258)

Isn't it interesting that about 200 of results just disappear?

**Comment by josdejong** [comment]
I'm not sure how I can help. Is there anything in `svelte-jsoneditor` that we can change to improve this? Or do we have to report something at `ajv` or pnpm or vite?

**Comment by Metehan-Altuntekin** [comment]
I'm not sure either. My best guess is it's Vite but I can't speak for sure without examining the code

**Comment by josdejong** [comment]
I think the next steps are:

- Create a minimal demo reproducing the issue
- Figure out if this is purely an issue with `ajv` and `vite`, or that it has to do with how `svelte-jsoneditor` uses `ajv` (i.e. rule out as much factors as possible)

Anyone able to help figuring this out?

**Comment by Metehan-Altuntekin** [comment]
I think I can create a demo repo in some of my free time. I'll add it to my Todo

**Comment by josdejong** [comment]
Thanks!

**Comment by Metehan-Altuntekin** [comment]
Sorry for the delay. I have been trying to avoid little things as possible.

I have just created the demo repo: (https://github.com/Metehan-Altuntekin/svelte-jsoneditor-pnpm-monorepo-issue-demo)

With the latest version of everything, the issue seems to be fixed.

**Comment by josdejong** [comment]
That is good news, thanks for the feedback 🎉
