### ISSUE TITLE
Hide "table" mode

### ISSUE THREAD

**Issue by jbek7** [josdejong/svelte-jsoneditor#272]
I don't see an option to configure hiding modes in documentation or at least hiding "table" mode. Is there a way to configure it?

**Comment by jbek7** [comment]
Never mind I see I can use: 
```
onRenderMenu: (items, context)=>{
                    return items.filter(v => v.text !== "table" && v.type === "button");
                }
```

**Comment by josdejong** [comment]
👍 

please note that hiding the menu button does not fully disable table mode, it can for example pop up when you select an array, right click the array, and then choose "Edit Array" from the context menu.
