### ISSUE TITLE
The form is being submitted when press Enter on tree mode

### ISSUE THREAD

**Issue by jbek7** [josdejong/svelte-jsoneditor#274]
I've a react-final-form component that wraps the SvetleJsonEditor. It's submitting form for some reason when I press enter after editing the JSON tree value.

**Comment by josdejong** [comment]
How can we reproduce your issue? Can you provide a minimal code example, like in https://codesandbox.io ?

**Comment by josdejong** [comment]
Closing this due to lack of input.

**Comment by javierjulio** [comment]
@josdejong I've started using the new library today and I've run into the same issue. We use the original jsoneditor library extensively all in forms. I confirmed that the original library when in tree mode and editing a value, hitting enter does not submit the form. With the new library it does. Would you prefer I open a new issue with the reproduction?

**Comment by javierjulio** [comment]
@josdejong I've opened a new issue in #498 since it is a bug and a reproduction is provided as requested. Thank you.
