### ISSUE TITLE
Feature-Request: onFocus event

### ISSUE THREAD

**Issue by howardjones** [josdejong/svelte-jsoneditor#276]
I'd like to be able to have other page elements  react to a change of focus in the JSON Editor - my use case is additional context-sensitive help per-field, but I think there are others. I don't think this exists currently. I also don't think (but it's not very clear what "selected" means in that context) that onSelect proposed in #163 does what I am looking for.

I am using the vanilla-jsoneditor with no frameworks.

**Comment by howardjones** [comment]
To the selection - I'm hoping to have a side-by-side layout providing additional info about the effects of changing the current value as a user edits the document. It does sound like I could use onRenderValue to do some cheesy jquery-style addition of data-xxx attributes with the path though and attach event handlers myself.

**Comment by josdejong** [comment]
Ok clear, then the `onSelect` event discussed in #163 will be what you need I think.

> It does sound like I could use onRenderValue to do some cheesy jquery-style addition of data-xxx attributes with the path though and attach event handlers myself.

That would be possible I think, though it may be relatively cumbersome. Properly implementing this `onSelect` in the editor is probably less work 😉 , help would be welcome.

**Comment by josdejong** [comment]
Closing this issue, an `onSelect` event is available since some time now.
