### ISSUE TITLE
Consuming through skypack fails

### ISSUE THREAD

**Issue by bebraw** [josdejong/svelte-jsoneditor#28]
I'm building [a small project](https://gustwind.js.org/) based on jsoneditor (thanks a lot!).

While porting from jsoneditor to svelte-jsoneditor, I noticed it doesn't build on skypack. Here's how to reproduce:

1. Head to https://cdn.skypack.dev/svelte-jsoneditor
2. Results in https://cdn.skypack.dev/error/build:svelte-jsoneditor@v0.3.3-mVTQdzwNsDlCzTQ7Ef5I

It's possible the problem is at skypack side as well but just thought to let you know consuming through skypack doesn't work at the moment.

**Comment by bebraw** [comment]
For reference, http://esm.sh/svelte-jsoneditor@0.3.3 seems to work.

**Comment by josdejong** [comment]
I've now split the library into two packages: 

- `svelte-jsoneditor` for usage in Svelte
- `vanilla-jsoneditor` for use in plain JavaScript and frameworks like SolidJS, React, Vue, etc

Switching to use `vanilla-jsoneditor` fixes this issue.

**Comment by anton-b** [comment]
for those who might be looking for it https://cdn.jsdelivr.net/npm/vanilla-jsoneditor@0.11.5/index.js
