### ISSUE TITLE
I got ReferenceError: document is not defined in nextjs project.

### ISSUE THREAD

**Issue by aholeye** [josdejong/svelte-jsoneditor#288]
<img width="539" alt="image" src="https://github.com/josdejong/svelte-jsoneditor/assets/26758630/6a1c7b75-899c-41fe-9ea4-7071d07b4934">
But, the page is displaying correctly.

**Comment by josdejong** [comment]
See docs about nextjs: https://github.com/josdejong/svelte-jsoneditor/blob/main/README-VANILLA.md#import-and-use-the-react-component

**Comment by aholeye** [comment]
It works! Thank you.

**Comment by aholeye** [comment]
I'm sorry, there is still an issue.
When I copy the demo according to the documentation, it works fine. However, when I add a prop mode={Mode.text}, the issue still persists.
like this:
```javascript
        <JSONEditorReact
          content={jsonContent}
          onChange={handler}
          mode={Mode.text}
        />
```

**Comment by aholeye** [comment]
After some testing, I have noticed an even stranger phenomenon. Even declaring `useState(Mode.tree)` within the page causes the same issue.
like this:
```javascript
  const [mode, setMode] = useState(Mode.tree)
```
even if I haven't used that variable.
