### ISSUE TITLE
How to display the table mode by default？

### ISSUE THREAD

**Issue by EasonBeaty** [josdejong/svelte-jsoneditor#289]
TypeScript

declare enum Mode {
    text = "text",
    tree = "tree",
    table = "table"
}

**Comment by EasonBeaty** [comment]
oh,sorry,I use vanilla-jsoneditor,

**Comment by josdejong** [comment]
See docs: https://github.com/josdejong/svelte-jsoneditor#properties

**Comment by EasonBeaty** [comment]
react frame
