### ISSUE TITLE
Why does the onChange cursor automatically jump to the beginning;

### ISSUE THREAD

**Issue by EasonBeaty** [josdejong/svelte-jsoneditor#293]
onChange={(value) => {
  this.setState({text:XXXX})
}}

**Comment by josdejong** [comment]
How can I reproduce your issue? 

It looks like your updating the state with `set` rather than `update`.

**Comment by EasonBeaty** [comment]
I figured out that the reason should be that after the set is re-rendered by the component, the cursor will automatically go to the beginning position

**Comment by EasonBeaty** [comment]
I used other method to achieve it and now it's ok
