### ISSUE TITLE
Lack of format and repair function on JSONEditor instance

### ISSUE THREAD

**Issue by cloydlau** [josdejong/svelte-jsoneditor#3]
Programmatically formatting and repairing as the older version does is much needed, thanks.

**Comment by josdejong** [comment]
Thanks for your input. Are you using the latest version? This version has a `code` mode again (toggle with the left most button in the main menu). The repair button is replaced with a proactive button "Repair automatically", which pops up in the error message when you have loaded invalid JSON.

![afbeelding](https://user-images.githubusercontent.com/568626/110987459-6429c680-836f-11eb-8077-68710da88752.png)

**Comment by cloydlau** [comment]
Yeah, I've used that sweet button. And I want to do the same thing in **programmatical** way, like automatically repair and format when **onBlur** is called. These popups is very sweet but I think it should be configurabal. (●'◡'●)

**Comment by josdejong** [comment]
Ahh, yes makes sense to expose methods `format`, `compact`, and `repair` so you can call them programmatically 👍 .

For your information: there is not much magic in those implementations, it boils down to:

```js
import jsonrepair from 'jsonrepair'

const indentation = 2

function format(text) {
  return JSON.stringify(JSON.parse(text), null, indentation)
}

function compact(text) {
  return JSON.stringify(JSON.parse(text))
}

function repair(text) {
  return jsonrepair(text)
}
```

**Comment by cloydlau** [comment]
Very elaborate! Thanks.
