### ISSUE TITLE
NPM Usability Enhancement for Visual Studio Scenario

### ISSUE THREAD

**Issue by bdbvb** [josdejong/svelte-jsoneditor#300]
When updating my NPM packages in Visual Studio... for most packages I can link over to the repository to look for changes.

![image](https://github.com/josdejong/svelte-jsoneditor/assets/11095196/c24f89ea-87f6-4d5c-adda-fb6fa5ed7e11)

The link for vanilla-jsoneditor points to the homepage at https://jsoneditoronline.org/. But there's no link from the homepage over to the repository, so I usually get there through Google, which takes a little longer.

An improvement might be to have a link to the git repo(s) from the homepage at https://jsoneditoronline.org/.

**Comment by josdejong** [comment]
Thanks for bringing this up, that is indeed not handy. I utilized two fields in the package.json: one for the homepage where you see the library in action, and one for the source repository ([see npm](https://www.npmjs.com/package/svelte-jsoneditor)):

![afbeelding](https://github.com/josdejong/svelte-jsoneditor/assets/568626/74479347-0207-4ff8-a1f1-b8033151851c)

There is indeed not an easy to find link to the github repo from the website https://jsoneditoronline.org/. I'll see if I can improve on that one way or another.

**Comment by josdejong** [comment]
I've change the `homepage` field to the Github repo. The Readme starts with the following section, so it will still be easy to try it out in the web application:

> A web-based tool to view, edit, format, transform, and validate JSON.
> 
> Try it out: https://jsoneditoronline.org
> 
> The library is written with Svelte, but can be used in plain JavaScript too and in any framework (SolidJS, React, Vue, Angular, etc).

**Comment by bdbvb** [comment]
Thanks, this is very helpful!
