### ISSUE TITLE
can we hide the 'x items' label?

### ISSUE THREAD

**Issue by aroman** [josdejong/svelte-jsoneditor#309]
i cannot find a prop or configuration property for this. also, THANK YOU for this _incredible_ tool.

![CleanShot 2023-09-14 at 20 07 00@2x](https://github.com/josdejong/svelte-jsoneditor/assets/531504/7c55be48-2703-49f6-83d3-6a5165b4af39)

**Comment by josdejong** [comment]
Thanks, good to hear Avi.

You can hide this 'x items' tag with some CSS. If there is much need for it, we can consider adding a configuration option for it.
