### ISSUE TITLE
vite: TypeError: Cannot set properties of undefined (setting 'j')

### ISSUE THREAD

**Issue by milahu** [josdejong/svelte-jsoneditor#31]
TLDR: how to actually use this library? 0__o
... project template?

when i run the example [json_schema_validation.svelte](https://github.com/josdejong/svelte-jsoneditor/blob/main/src/routes/examples/json_schema_validation.svelte), i get the error

> Uncaught SyntaxError: The requested module '/node_modules/.pnpm/debug@4.3.2/node_modules/debug/src/browser.js?v=ab0664fe' does not provide an export named 'default'

from

https://github.com/josdejong/svelte-jsoneditor/blob/8e5aecf4b0ac29c97d545098f037d7f027182558/src/lib/components/modals/popup/AbsolutePopup.svelte#L4

### backtrace

```js
// node_modules/debug/src/browser.js

module.exports = require('./common')(exports);
```

```js
// node_modules/debug/src/common.js

function setup(env) {
        createDebug.debug = createDebug;
        // ...
        return createDebug;
}

module.exports = setup;
```

looks like a problem with vite and commonjs ...

### reproduce

```sh
npm i -g pnpm
pnpx create-vite frontend --template svelte
cd frontend
pnpm install svelte-jsoneditor
cd src
curl -L -o App.svelte https://github.com/josdejong/svelte-jsoneditor/raw/main/src/routes/examples/json_schema_validation.svelte
sed -i 's/\$lib/svelte-jsoneditor/' App.svelte
cd ..
npm run dev
```

### related

also pnpm does not run the `prepare` script when i install from git ...

```
npm rm svelte-jsoneditor
pnpm i https://github.com/josdejong/svelte-jsoneditor.git

stat node_modules/svelte-jsoneditor/dist
stat: cannot statx 'node_modules/svelte-jsoneditor/dist': No such file or directory
```

**Comment by milahu** [comment]
probably a bug in pnpm
after `pnpm i svelte-jsoneditor` i still had the git version in node_modules

clean install with the npm version `svelte-jsoneditor`

```
rm -rf node_modules
pnpm install

stat node_modules/svelte-jsoneditor/dist
  File: node_modules/svelte-jsoneditor/dist
  Size: 4096      	Blocks: 8          IO Block: 4096   directory

```

**Comment by milahu** [comment]
fixed by using rollup

https://github.com/milahu/svelte-jsoneditor-template

**Comment by milahu** [comment]
> also pnpm does not run the `prepare` script when i install from git ...

it does, but the `prepare` script is wrong

prepare should build the package = produce `node_modules/svelte-jsoneditor/dist`

**Comment by milahu** [comment]
> prepare should build the package = produce `node_modules/svelte-jsoneditor/dist`

workaround in https://github.com/milahu/svelte-jsoneditor/tree/fix-install-from-git
related issue https://github.com/sveltejs/kit/issues/2772

**Comment by josdejong** [comment]
Thanks @milahu for looking into this. I have to find some time to read your comments and understand the issue.

Is this related to the known issues that sveltekit+vite have with non-ES libraries (see https://github.com/sveltejs/kit/issues/928)? For that I found a workaround described in the readme: https://github.com/josdejong/svelte-jsoneditor#sveltekit-setup

**Comment by milahu** [comment]
multiple issues

* a bug in `pnpm` which sometimes fails to re-install packages - out of scope here
* a bug in the `debug` module, so that the node version is imported, but we need the browser version, fixed in https://github.com/milahu/debug/commits/patch-1 - or we can wait ~10 years for an [official ESM release of the debug package](https://github.com/visionmedia/debug/pull/852#issuecomment-943424234) cos people are so good in keeping their promises /s
* [installing sveltekit packages from git](https://github.com/sveltejs/kit/issues/2772) requires a workaround, cos sveltekit is designed to produce NPM packages ... which of course is a feature, not a bug : P

> workaround described in the readme: https://github.com/josdejong/svelte-jsoneditor#sveltekit-setup

with the `viteOptimizeDeps` workaround, it broke even more in my case ^^

currently im not using this (svelte-jsoneditor)

**Comment by josdejong** [comment]
Wow that's quite a list 😅 

Since SvelteKit is still in beta, and there are known issues with Vite and commonjs packages, I think it makes sense to wait until those issues are sorted out before putting a lot of effort into workarounds. 

If specifically the `debug` library is problematic, we could see if we can replace it with an other, similar package.

**Comment by milahu** [comment]
> putting a lot of effort into workarounds

the workarounds are working, so the only effort is copy-paste

> it makes sense to wait

i would want my library to be usable not ["perfect"](https://duckduckgo.com/?q=perfectionism&ia=web) ...

but hey, its your library ; )

**Comment by josdejong** [comment]
Yes, this will solve the issues _you're_ having with _your_ pnpm setup. But there are _plenty_ of different setups and built tools and circumstances all having their own quirks, I want to be careful not ending up with a huge patchwork 😅.

If the `debug` library is the only issue here, I prefer looking into an alternative lightweight debugging library, or write it ourselves. Just something simple to be able to do logging without having to use `console.log` basically :)

**Comment by milahu** [comment]
i have to admit, my sveltekit workaround requires posix shell ... give me two seconds

**Comment by milahu** [comment]
see [svelte.prepare.mjs](https://github.com/milahu/svelte-jsoneditor/blob/fix-install-from-git/svelte.prepare.mjs)

**Comment by josdejong** [comment]
Thanks for sharing. So this is a prepare script that you can use if you are using pnpm?

**Comment by josdejong** [comment]
Will close this issue now due to inactivity, feel free to reopen if this is still an issue.
