### ISSUE TITLE
Cannot paste text in the search box input field in tree mode

### ISSUE THREAD

**Issue by shakedlerer** [josdejong/svelte-jsoneditor#315]
Expected Result
Pasted text in search-box should be searched within current json document opened

Actual Result
Pasted text being inserted into current json document opened 

Steps to reproduce
1) Open existing json document to be viewed in jsoneditoronline.org
2) Open search-box within same document
3) Paste any text in search-box to be searched within document

Screen recorded issue - https://youtu.be/6VDmuPU_Dfo
Issue appeared in multiple devices

Thanks

**Comment by josdejong** [comment]
Thanks for reporting, I can reproduce the issue. Will fix it asap.

**Comment by josdejong** [comment]
Fixed now in `svelte-jsoneditor@0.18.7` and JSON Editor Online v6.13.10.
