### ISSUE TITLE
Option to disable message popup

### ISSUE THREAD

**Issue by alpreu** [josdejong/svelte-jsoneditor#328]
Hi I'm wondering if there is a way to disable the message popup?
I can see setting `askToFormat` to false disables the popup for formatting.
However, I also want to hide/disable the error popup that says e.g. `Unexpected token 'a', "abc" is not valid JSON`. Is that possible?

**Comment by josdejong** [comment]
If you don't want to see parse error messages at the bottom, you can hide this section using CSS.

**Comment by alpreu** [comment]
> If you don't want to see parse error messages at the bottom, you can hide this section using CSS.
Yeah that's an option, I was just wondering if there is a way to switch the whole verification logic itself off (including the icons next to the line number etc)

**Comment by josdejong** [comment]
If there is a good use case for it and more people that need it we can consider that. What is your use case?

**Comment by alpreu** [comment]
> If there is a good use case for it and more people that need it we can consider that. What is your use case?

I'm not sure if it's a really a common usecase. They way I'd like to use it is basically as more of a json highlighter than a json parser in the sense that I don't care if the user input is valid json or not

**Comment by josdejong** [comment]
👍 

Maybe you don't need `svelte-jsoneditor` and you can just use CodeMirror without extra ceremony.
