### ISSUE TITLE
Switching to text mode changes the style or font (...using AdminLTE) 

### ISSUE THREAD

**Issue by Th3R3alDuk3** [josdejong/svelte-jsoneditor#337]
Hi, I use AdminLTE and have integrated the JSONEditor into my site. 
Every time I switch to text mode, the font and size of the `.jse-menu` changes. 

![ezgif com-video-to-gif](https://github.com/josdejong/svelte-jsoneditor/assets/60510941/1b296595-c86c-4f14-b7f0-b8f30e87d81b)

I had a look and the CSS class `.jse-text-mode` has no font change (`font-family: var(--jse-font-family-mono);` or `font-size: var(--jse-font-size-mono);`). This automatically uses the font of the `.jse-main` class.

![Unbenannt](https://github.com/josdejong/svelte-jsoneditor/assets/60510941/4b8022d6-3e3b-49b7-ad3a-c49b1e0acab2)

No idea why it works otherwise.

Here is sample code...

[https://codepen.io/Th3R3alDuk3/pen/GRzWJZd](https://codepen.io/Th3R3alDuk3/pen/GRzWJZd)

**Comment by josdejong** [comment]
Thanks for reporting. The sample code helped me a lot to see what's going on. Fixed now via 2eec4e6 (not yet published)

**Comment by josdejong** [comment]
The fix is now published in `v0.18.2`
