### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by houcemL** [josdejong/svelte-jsoneditor#347]
Hello

Thanks for the editor, i was wonderring if there is a way to translate labels like 'text' to 'texte' in french or other language ? 
It would be very helpfull to add translation if it does not exist

**Comment by josdejong** [comment]
Thanks for your input! There is not yet support for translations. That would be very welcome to have though.

Let's continue this discussion in https://github.com/josdejong/svelte-jsoneditor/discussions/336.
