### ISSUE TITLE
Transfer everything to svelte 5

### ISSUE THREAD

**Issue by AlexRMU** [josdejong/svelte-jsoneditor#373]
When it will be possible.

**Comment by AlexRMU** [comment]
And by the way, look at this: https://jsonjoy.com/
They have:
- fastest JSON serialization and deserialization algorithms in NPM ecosystem
- fast json-patch 
- and other packages for working with json that can be useful or speed up the application

**Comment by josdejong** [comment]
> Transfer everything to svelte 5

Definitely, I can't wait for it :). I created a branch [feat/sveltekit2](https://github.com/josdejong/svelte-jsoneditor/tree/feat/sveltekit2) today to upgrade to [SvelteKit 2](https://svelte.dev/blog/sveltekit-2). The branch still has a few issues that need to be resolved. Besides that, all dependencies are quite up to date.

> And by the way, look at this: https://jsonjoy.com/

That is definitely an interesting collection. Are there specific things in this regard that you think should be improved on the current library? In that case, can you open a separate issue to discuss it?

**Comment by AlexRMU** [comment]
https://jsonjoy.com/libs/json-joy-js/json-binary for storage

https://jsonjoy.com/libs/json-joy-js/json-pack/json instead of built in `JSON`
(measure the speed in different browsers with different json sizes)

copy or use it here and in the immutable-json-patch, if it's better that way
https://jsonjoy.com/libs/json-joy-js/json-patch
https://jsonjoy.com/libs/json-joy-js/json-pointer
https://jsonjoy.com/libs/json-joy-js/json-equal
https://jsonjoy.com/libs/json-joy-js/json-clone

**Comment by josdejong** [comment]
Thanks for your inputs. 

An alternative JSON parser can already be used in `svelte-jsoneditor` using the `parser` option. The advertised speed of json-joy looks impressive!

In the source code of `svelte-jsoneditor` we do use `isEqual` from Lodash here and there. It can be interesting to see if the deep quality check of jsonjoy results in an improved performance. If someone likes to give that a try please open a new issue to do an experiment and discuss the results.

**Comment by AlexRMU** [comment]
json-pack can be used instead of the built-in json or only on the site

**Comment by josdejong** [comment]
Closing this issue now, we'll update to Svelte 5 as soon as it is released.
