### ISSUE TITLE
Edit Object as Table

### ISSUE THREAD

**Issue by TonyValenti** [josdejong/svelte-jsoneditor#382]
If you have a JSON dictionary like this:
```json
{
    "1": {
      "0": "Hidden",
      "is_firm_specific": 0,
      "is_deletable": 0,
      "is_viewable": 0
    },
    "2": {
      "0": "Automatic",
      "is_firm_specific": 0,
      "is_deletable": 0,
      "is_viewable": 0
    },
    "3": {
      "0": "Form Created",
      "is_firm_specific": 0,
      "is_deletable": 0,
      "is_viewable": 0
    },
    "4": {
      "0": "Form Edited",
      "is_firm_specific": 0,
      "is_deletable": 0,
      "is_viewable": 0
    },
    "5": {
      "0": "Form Completed",
      "is_firm_specific": 0,
      "is_deletable": 0,
      "is_viewable": 0
    },
}
```

It would be really nice to be able to view it in table mode.

**Comment by josdejong** [comment]
I think this is not a very common case, but if there is much use for it we can consider implementing support.

What you can do right now is:

- Open the document in the JSON Editor
- Right click the root object, select "Convert to: Array"
- Switch to table mode
- When done editing, to to tree mode again, and convert the array into an object again.

**Comment by josdejong** [comment]
Closing this issue now, we con reopen if there turns out to be a broad need for it.

**Comment by JoeSzymkowiczFiveM** [comment]
I would definitely use this. I just setup this package, only to find this mode unusable. Hopefully support is added in the future.
