### ISSUE TITLE
No types when importing from standalone.js

### ISSUE THREAD

**Issue by iamEAP** [josdejong/svelte-jsoneditor#386]
When upgrading from `v0.19.0` to `v0.20.0`+,  if I choose to use the fully bundled version (via `import { JSONEditor } from 'vanilla-jsoneditor/standalone.js'`) in my typescript code, I get a `Could not find a declaration file for module 'vanilla-jsoneditor/standalone.js'` error.

Would it be possible to duplicate or ship typescript definitions for the standalone version as well?

**Comment by josdejong** [comment]
Thanks for reporting. I'll add a `standalone.d.ts`, I guess the `index.d.ts` is not enough.

**Comment by josdejong** [comment]
Should be fixed now in `v0.21.2`.
