### ISSUE TITLE
Making svelte-jsoneditor a widget for django

### ISSUE THREAD

**Issue by thclark** [josdejong/svelte-jsoneditor#389]
## Thanks and a neat link

Hi, @josdejong and the other @maintainers - I wanted to reach out and thank you, as the work you've done with this library and its predecessor has made a really massive impact on data management globally.

Over at [octue](github.com/octue), we develop OSS tools for data management, working on the border of science/industry in renewables/cleantech, so we've seen this first-hand in the drive of the wind and solar industries toward digitalisation.

The main reason for creating this issue (other than saying 👋) is that we've been developing an [integration into django](https://github.com/octue/django-svelte-jsoneditor) which has been turning out nicely, and just thought you might like to know about it. There are a few teething problems we'll sort out over time but it's basically there. Hope it helps someone!

Thanks again,

Tom and the Octue team.

**Comment by josdejong** [comment]
Thanks for open sourcing your Django widget, and thanks for supporting me Tom, appreciated!

I've added your Django integration to the list with wrapper libraries: https://github.com/josdejong/svelte-jsoneditor#wrapper-libraries-for-specific-frameworks
