### ISSUE TITLE
losing focus doesnt stop field edit

### ISSUE THREAD

**Issue by dranitski** [josdejong/svelte-jsoneditor#40]
![image](https://user-images.githubusercontent.com/27373393/145835793-fef183e8-060e-4e51-b1cd-053177339658.png)
clicking outside the editor does not stop the field edit. Old `jsoneditor` work fine here - it stops field edit on clicking outside of himself

**Comment by josdejong** [comment]
Good point, thanks

**Comment by josdejong** [comment]
I created a partial fix. It's important to keep the edit field open when you for example want to switch between the editor and an other application to copy or paste something. So the editing should be stopped when clicking outside of the editor only.

**Comment by josdejong** [comment]
Ok created a well working fix now

**Comment by josdejong** [comment]
Fix is published now in `v0.3.10`
