### ISSUE TITLE
Big bundled size

### ISSUE THREAD

**Issue by NormandoHall** [josdejong/svelte-jsoneditor#413]
Hi! Thanks for this excelente editor.

I am including in a sveltekit project and runs like a charm, but I'm concerned about the bundled size, 500Kb for server and 1Mb for client.

![image](https://github.com/josdejong/svelte-jsoneditor/assets/2943127/5d6befc8-a022-4bdd-b726-1d5f250bff0d)

![image](https://github.com/josdejong/svelte-jsoneditor/assets/2943127/8733930b-49d0-48bc-84ea-e0a75cda90c0)

I am missing something?

sveltekit v.2.5.3
svelte v4.2.12
svelte-jsoneditor v0.22.0

**Comment by josdejong** [comment]
That is indeed the size of the editor. You can also check out the size of the `standalone.js` file in the vanilla package: https://unpkg.com/browse/vanilla-jsoneditor/, currently 1.3 MB, or 381KB when gzipped. When comparing this with the `index.js` file in this package (580 KB, or 150 KB when gzipped), you can get an idea of the size of dependencies like `codemirror`, `ajv`, `jsonrepair`, etc in that. The `index.js` file does not bundle the external npm dependencies, the `standalone.js` file does.

**Comment by NormandoHall** [comment]
@josdejong thanks for the explanation.

regards
