### ISSUE TITLE
Error not displayed when only "" is entered

### ISSUE THREAD

**Issue by zehawki** [josdejong/svelte-jsoneditor#414]
No error alert is displayed when only `""` is entered in the editor. Surely this is not valid json, or?

![image](https://github.com/josdejong/svelte-jsoneditor/assets/8095144/ad247a94-0948-4db9-b4de-e4a0b75ed74f)

Similar this `[""]` also doesnt give an error.

**Comment by josdejong** [comment]
An empty string `""` is indeed valid JSON.
