### ISSUE TITLE
Allow to override the copy to clipboard function

### ISSUE THREAD

**Issue by kimpixel** [josdejong/svelte-jsoneditor#425]
In some cases the editor runs in a uncontrolled iframe.
without the `allow="clipboard-read; clipboard-write"` tag it was not posible to copy and paste.

a new parameter (callback) to overwrite the copy function will help to redirect the functionality to the parent frame.

**Comment by josdejong** [comment]
Thanks for reporting. Can you share a minimal code example demonstrating the issue? It sounds like defining this `allow="clipboard-read; clipboard-write"` for your iframe solves the problem, so is there actually an issue?

**Comment by kimpixel** [comment]
Try to copy on you own example:
https://www.sveltelab.dev/q1l38ztdys4at87
Chrome ist effected.

"uncontrolled iframe" means - no access to the iframe itself.

**Comment by josdejong** [comment]
Thanks. I opened your example in both Firefox and Chrome, use `tree` mode, and copied something via both `Ctrl+C` and the Copy button in the context menu. Both work fine. Which steps do you exactly do that throw this issue?

**Comment by josdejong** [comment]
Closing due to lack of response. Please reopen if still relevant.
