### ISSUE TITLE
OnSelect - KeySelection & ValueSelection both return KeySelection

### ISSUE THREAD

**Issue by echan00** [josdejong/svelte-jsoneditor#429]
Submitting a separate issue relating to `OnSelect`. 

I'm not that experienced, so maybe this is a false positive. But I see that KeySelection and ValueSelection are both returning the value of the Key.

<img width="861" alt="Screenshot 2024-05-01 at 12 19 10 PM" src="https://github.com/josdejong/svelte-jsoneditor/assets/6287299/c1186f55-7cb1-4fe6-9b5e-f4b7e8efd043">

**Comment by josdejong** [comment]
This is indeed a false positive, but I understand the confusion.

When you select either a key or a value, they both have the same path. You can distinguish them only by looking at whether the `type` is `key` or `value`. The value itself is not part of the path. Try for example with the Lodash function `get` what happens:

```js
import { get } from 'lodash-es'
 
const json = {
  'string': 'Hello World'
}

console.log(get(json, ['string'])) // will print "hello World"
```

**Comment by echan00** [comment]
Makes sense. The json is accessible so agree the key is really good enough in this case
