### ISSUE TITLE
Menu color switching

### ISSUE THREAD

**Issue by Gzzzxx** [josdejong/svelte-jsoneditor#432]
May I ask how the menu switches to follow the theme

**Comment by josdejong** [comment]
See:

- https://github.com/josdejong/svelte-jsoneditor?tab=readme-ov-file#styling
- https://github.com/josdejong/svelte-jsoneditor/blob/main/examples/browser/custom_theme_color.html
- https://github.com/josdejong/svelte-jsoneditor/blob/main/src/routes/examples/custom_theme_color/%2Bpage.svelte

**Comment by Gzzzxx** [comment]
Problem solved, thank you very much
