### ISSUE TITLE
Open a link via Ctrl + Click doesnt work

### ISSUE THREAD

**Issue by derldalfor100** [josdejong/svelte-jsoneditor#436]
Please fix it or provide a better way other than Ctrl + Enter to open a link

**Comment by josdejong** [comment]
Thanks for your input. I just tested and Ctrl+Enter works fine to open urls. How can I reproduce your issue exactly?

**Comment by derldalfor100** [comment]
Hi @josdejong, Ctrl+Enter works for me too however Ctrl + Click doesnt work. You can reproduce that in the playground. The title attribute guides us both ways should work.

**Comment by josdejong** [comment]
I've opened the [playground example](https://www.sveltelab.dev/q1l38ztdys4at87) in Firefox and Chrome, there Ctrl+Enter and Ctrl+Click on a url does work as expected (opening the url in a new tab).

What browser/OS are you using?

**Comment by derldalfor100** [comment]
@josdejong Sorry for the misunderstanding. I'm using version 0.23.2 of vanilla-jsoneditor. And as you can see here https://jsoneditoronline.org/#left=local.bajowo&right=local.ramawi it doesnt work with Ctrl + Click. I'm using Brave and Chrome.

**Comment by derldalfor100** [comment]
@josdejong One more note. The bug doesn't happen in Windows. Im mainly using Mac and it appears also in the Svelte playground.

**Comment by josdejong** [comment]
> The bug doesn't happen in Windows.

Ah, now that is a clear clue. I'm indeed running Windows. So, probably the mapping for the Command key doesn't work as it should. 

Help debugging this issue would be welcome, it's not easy for me to test in a reliable way.

**Comment by josdejong** [comment]
This issue has been fixed now in `v0.23.6`.
