### ISSUE TITLE
Create a VueJS based sample (just as there is for REACT)

### ISSUE THREAD

**Issue by brianpos** [josdejong/svelte-jsoneditor#44]
I started this one and got close, but had some issues with it (still learning VueJS too) - based on the REACT demo that you have
https://codesandbox.io/s/svelte-jsoneditor-vue-h7yz8
(and didn't get that close in my actual project I want it in either)
This sample sandbox does display the editor, but that's about all at this point - will give it a break for a while and do some more learning.

**Comment by josdejong** [comment]
Ah, nice start. I see you create an editor, but doesn't yet pass any contents to it and are not yet listening for changes made in the editor.

**Comment by josdejong** [comment]
I've reacted a Vue example and listed it in the [examples](https://github.com/josdejong/svelte-jsoneditor#examples) section of the readme.

CodeSandbox: https://codesandbox.io/s/svelte-jsoneditor-vue-toln3w
