### ISSUE TITLE
Does vanilla-jsoneditor not support table mode

### ISSUE THREAD

**Issue by qq1031824970** [josdejong/svelte-jsoneditor#441]
![image](https://github.com/josdejong/svelte-jsoneditor/assets/85598470/24928647-46aa-4195-9b4d-99874c0bc86f)
![image](https://github.com/josdejong/svelte-jsoneditor/assets/85598470/328db943-6efa-4dea-8c57-326751d7415e)

 As shown in the picture, I can't find the table mode

**Comment by josdejong** [comment]
Can you please translate your question in English?

**Comment by qq1031824970** [comment]
Does vanilla-jsoneditor not support table mode

**Comment by qq1031824970** [comment]
Sorry, I opened the demo directly and forgot the version.

**Comment by qq1031824970** [comment]
do you have idea to add i18n

**Comment by josdejong** [comment]
> Sorry, I opened the demo directly and forgot the version.

Thanks for pointing this out, I've now updated all demos to the latest version.

> do you have idea to add i18n

Not yet, help adding i18n would be welcome.
