### ISSUE TITLE
The standalone js file is not aligned to the latest version

### ISSUE THREAD

**Issue by derldalfor100** [josdejong/svelte-jsoneditor#445]
https://cdn.jsdelivr.net/npm/vanilla-jsoneditor/standalone.js - is not the latest stable version. I saw it has been used in the playgrounds and in the README files. Though, the minified version is indeed aligned to the latest stable version.

**Comment by josdejong** [comment]
Maybe the CDN is a bit behind or there is some caching involved or so? It may be resolved tomorrow.

**Comment by josdejong** [comment]
You can also use a specific version: https://cdn.jsdelivr.net/npm/vanilla-jsoneditor@0.23.6/standalone.js

**Comment by derldalfor100** [comment]
Thanks. Looks like CDN caching issue, now it works as expected.
