### ISSUE TITLE
When using the editor, if it is an empty object, initializing and editing an empty object will result in an error. How should this be resolved？

### ISSUE THREAD

**Issue by ollgh** [josdejong/svelte-jsoneditor#449]
![image](https://github.com/josdejong/svelte-jsoneditor/assets/38758049/8bdb6ddf-fdb8-4ac3-95e6-93467cb8f5f9)

**Comment by josdejong** [comment]
Thanks for reporting. Can you explain the exact steps to reproduce this issue?

**Comment by josdejong** [comment]
Closing due to a lack of response.
