### ISSUE TITLE
Read-only mode

### ISSUE THREAD

**Issue by ashkov** [josdejong/svelte-jsoneditor#456]
Hello!
Can I get just formatted JSON without possibility to edit it and without menus?

Thank a lot.

**Comment by ashkov** [comment]
`      const editor = new JSONEditor({
        target: document.getElementById('jsoneditor'),
        props: {
          content,
          mainMenuBar: false,
          statusBar:false,
          readOnly:true,
          mode:'text',
        }
      })`

**Comment by josdejong** [comment]
That will indeed show readonly JSON data with code highlighting. 

If you just need highlighted code though I think using `svelte-jsoneditor` is overkill. Using a code highligher like [PrismJS](https://prismjs.com/) or [highlight.js](https://highlightjs.org/) will be more lightweight I expect.
