### ISSUE TITLE
UnknownError: Internal error.

### ISSUE THREAD

**Issue by JeremyGood** [josdejong/svelte-jsoneditor#459]
For some reason, after a recent cleansing of my cookies and such, every time I try to open a document in jsoneditoronline, I get the error message: UnknownError: Internal error.

I have no idea why. This never used to happen to me.

I just subscribed to your no ad service, but I still have the problem.

jgoodell000@gmail.com
Jeremy Goodell

![image](https://github.com/josdejong/svelte-jsoneditor/assets/4039917/22e891f7-d8e7-4c70-ac7d-e02605de8364)

**Comment by josdejong** [comment]
Thanks for reporting Jeremy. Can you explain the issue in a bit more detail?

1. What browser are you using?
2. Can you make sure the latest version of the web application is loaded? You can check that via the menu Help > About, it should show "Current version: 7.0.5". If not, you can enforce reloading the latest version via Ctrl+F5.
3. Do you try to load an existing local document (not a cloud document)? Via what steps exactly do you open the document exactly? (via url, or via the menu File > Open?)
4. Can you try to collect more information about the error for me? Open your developer console (Ctrl+Shift+I or F12), and in the console, see if there is a more detailed error message and/or stacktrace.

**Comment by josdejong** [comment]
Any feedback @JeremyGood ?

**Comment by josdejong** [comment]
Closing due to a lack of response. Please reopen if still relevant.
