### ISSUE TITLE
text readOnly BUG

### ISSUE THREAD

**Issue by 07ke** [josdejong/svelte-jsoneditor#466]
![image](https://github.com/user-attachments/assets/2b318d30-f9bd-4c4f-aa0e-f8fe13d77bc2)
![image](https://github.com/user-attachments/assets/3e47fd4c-c1fd-451b-9d82-26e386745fe5)

"version": "0.23.7"

**Comment by josdejong** [comment]
Duplicate of https://github.com/josdejong/svelte-jsoneditor/issues/464
