### ISSUE TITLE
askToFormat also need auto action

### ISSUE THREAD

**Issue by belaviyo** [josdejong/svelte-jsoneditor#467]
According to the documentation, I couldn't find a property that allows the editor to automatically format JSON upon loading without user consent. Is there a way to automatically format the JSON in text mode without prompting the user?

**Comment by josdejong** [comment]
You can format the JSON yourself if you want, right before loading your document into the editor. See https://github.com/josdejong/svelte-jsoneditor/issues/3#issuecomment-803282031

**Comment by belaviyo** [comment]
Right. Thanks!
