### ISSUE TITLE
Getting error: Unexpected token (Note that you need @rollup/plugin-json to import JSON files)

### ISSUE THREAD

**Issue by imrabti** [josdejong/svelte-jsoneditor#47]
I followed the Readme instruction as described, but when I start the project I get the following error: 

```
[!] Error: Unexpected token (Note that you need @rollup/plugin-json to import JSON files)
node_modules/ajv/dist/refs/json-schema-draft-07.json (2:11)
```

Is there a step that I'm missing ? 
Does this component requires an older version of Svelte ?

**Comment by josdejong** [comment]
Hi Mrabti, I've only tested the library with SvelteKit, I'm not sure if that makes a difference. If so I suppose you'll have to add the mentioned `@rollup/plugin-json` plugin to your setup?

**Comment by josdejong** [comment]
🎉
