### ISSUE TITLE
How to use editor full screen mode?

### ISSUE THREAD

**Issue by ekzobrain** [josdejong/svelte-jsoneditor#475]
I see that there is some kind of support for editor fullscreen mode. At least it is available here: https://jsoneditoronline.org
But it is activated not from main menu bar, but from some outer demo component. At the same time fullscreen exit button is located inside main menu bar. How may I trigger fullscreen mode pragmatically (for example editor.enterFullScreen()) or activate a button in main menu bar?

**Comment by josdejong** [comment]
Two ingredients:

1. you control the size and positioning of the `DIV` where you create the editor yourself. You can toggle a class like `fullscreen` on it which positions the DIV absolutely, filling the whole screen.
2. You can add custom buttons to the menu of the editor using `onRenderMenu`, like add a button to enter/exit fullscreen
