### ISSUE TITLE
Trying to open a large file in code mode causes editor layout to overflow

### ISSUE THREAD

**Issue by MaDKaTZe** [josdejong/svelte-jsoneditor#48]
I've been trying to open a relatively large (around ~150 MiB) in code mode, for which the editor seems to raise a warning that this could browser to hang. Since the file is minified, however, the last editor line seems to have a calculated width of 1.08636e+09 px which causes the editor layout to overflow (screenshot below):

![layout-overflow](https://user-images.githubusercontent.com/963759/158592516-f9b1e137-89b9-49cd-b586-d3478532e5c2.png)

**Comment by josdejong** [comment]
Thanks for reporting, I can indeed reproduce this when opening a large, minified/compact JSON document.

**Comment by josdejong** [comment]
Fixed via 5574d38164f48610842a0707be81cf9ca12bd53b, library version `0.3.24`, web application version `6.0.0-beta.33`
