### ISSUE TITLE
Strange behavior when using vanilla-jsoneditor with radix-ui/react-tabs

### ISSUE THREAD

**Issue by rockonyu** [josdejong/svelte-jsoneditor#480]
I am developing with React and using the JsonEditor.tsx component provided in the documentation. However, I've encountered some strange behavior when using it in conjunction with @radix-ui/react-tabs:

1. JsonEditor defaults to text mode.
2. I edit the JSON in text mode.
3. While keeping the focus on JsonEditor, I switch to Tab 2.
4. The input field in Tab 2 becomes uneditable.

It seems that manually moving the focus out of JsonEditor before switching tabs can avoid this issue. I would like to understand what might be causing this behavior.

https://github.com/user-attachments/assets/bb258bf3-662a-48ee-9382-c1b26ba89667

https://stackblitz.com/edit/vitejs-vite-fppyvx?file=src%2FApp.jsx

**Comment by josdejong** [comment]
That sounds really curious indeed 🤔 

I've repeated the steps from your movie in the stackblitz example that you've provided but I can't reproduce the issue: all works as expected. I tried in both Firefox and Chrome.

Do you see any errors or anything in your developer console?

**Comment by rockonyu** [comment]
At the time, I was using Arc Browser version 1.56.0. Based on your feedback, I also installed Chrome and Firefox, and they both work fine.

It seems that this issue is not related to the package. I appreciate you taking the time to help me clarify the problem, and thank you for your quick reply.
