### ISSUE TITLE
Mode switching issue in React

### ISSUE THREAD

**Issue by MatthewAMartin** [josdejong/svelte-jsoneditor#482]
Hi! 

I'm using this as part of a React-based page editor I've been building with Editor.js. However, I'm having one particular issue with mode switching. For the first instance of the jsoneditor on the page, if you try to switch modes via the menu the following errors are thrown:

![Screenshot 2024-09-09 at 9 01 29 AM](https://github.com/user-attachments/assets/19585902-4b0f-4cf8-98a9-37160e98685b)

This then breaks mode switching on all other instances as well. But if you never interact with the mode switch on the first instance, the following instances will work as intended.

Any ideas as to what could be causing this issue?

Here's my current implementation:

![Screenshot 2024-09-09 at 9 00 04 AM](https://github.com/user-attachments/assets/ee35580b-f13a-4056-87df-71919eb61963)

**Comment by josdejong** [comment]
THanks for reporting. Can you create a minimal example on for example [StackBlitz](https://stackblitz.com/) so we can demonstrate the issue? For example in the React example https://codesandbox.io/p/sandbox/svelte-jsoneditor-react-59wxz switching mode works fine.

**Comment by josdejong** [comment]
Closing due to a lack of response. Please reopen if needed.
