### ISSUE TITLE
JMES Query not working in JSONeditor

### ISSUE THREAD

**Issue by amhaats1** [josdejong/svelte-jsoneditor#483]
Sample JSON

```json
{
  "locations": [
    {"name": "Seattle", "state": "WA"},
    {"name": "New York", "state": "NY"},
    {"name": "Bellevue", "state": "WA"},
    {"name": "Olympia", "state": "WA"}
  ]
}
```

Trying to perfom query 

```
locations[?state == 'WA'].name | sort(@) | {WashingtonCities: join(', ', @)}
```

Getting syntax error
```
SyntaxError: Unexpected token '?'
```

I can put the same JSON in https://jmespath.org/

and get the proper return

Result
```json
{
  "WashingtonCities": "Bellevue, Olympia, Seattle"
}
```

**Comment by josdejong** [comment]
How can I reproduce your issue?

**Comment by josdejong** [comment]
I think that you have not selected/loaded the JMESPath query language and are using Lodash instead. You can select a query language via the gear icon top right of the Transform modal.

**Comment by amhaats1** [comment]
Thank you very much and for the very fast response, that did the trick!!!
