### ISSUE TITLE
'isMac' is referenced directly or indirectly in its own type annotation.

### ISSUE THREAD

**Issue by in-vbonilla** [josdejong/svelte-jsoneditor#486]
Hello,

I am upgrading the dependencies from my Angular project, and when I set vanilla-jsoneditor from v1.0.0 and beyong, I am getting an error.

![imagen](https://github.com/user-attachments/assets/2c28d97c-9dfe-43f7-8411-78b3208c3be5)

Downgrading to previous version (0.23.7) does not throw any error.

Many thanks for your work!

**Comment by josdejong** [comment]
Thanks for reporting. Apparently the TypeScript types are messed up for some reason when generating the index.d.ts, in the code there is no naming conflict: 

https://github.com/josdejong/svelte-jsoneditor/blob/4263d6fd9ce36404170cdb828378a399dbdc9649/src/lib/utils/keyBindings.ts#L22

I'll change the name to solve this issue.

**Comment by josdejong** [comment]
Fixed now in `v1.0.4`

**Comment by in-vbonilla** [comment]
Thanks!!
