### ISSUE TITLE
Inquiry About JSON Query Script for Removing Time Information

### ISSUE THREAD

**Issue by jemid21** [josdejong/svelte-jsoneditor#500]
Dear
I hope this message finds you well.

I am a regular user of your online JSON editor and appreciate the functionality it offers. I am currently working with JSON files that include date and time information, and I need to remove the time portion while keeping only the date.

Would you happen to have or know of a specific JSON Query script that could accomplish this task? If not, could you guide me on how to write such a script or modify existing data to achieve this goal?

Your assistance would be greatly appreciated, as it will help streamline my workflow.

Thank you in advance for your support, and I look forward to hearing from you.

Best regards,

[
[planning_sorted 09.53.39.json](https://github.com/user-attachments/files/17784074/planning_sorted.09.53.39.json)
](url)

**Comment by josdejong** [comment]
Good question!

The [JSON Query language](https://jsonquerylang.org/) does not (yet) have support for manipulating strings or work with dates. 

What you can do is switch to JavaScript+Lodash via the toggle top right of the Transform Modal, [see docs](https://jsoneditoronline.org/docs/#transform):

![transform_switch_query_language COCD6UuP_2wBK4T](https://github.com/user-attachments/assets/2083d188-e8f2-410c-9b6e-8bdcc162019f)

When using JavaScript as query language, you have all freedom to do stuff with strings and dates, so in case of an ISO date string you can pick just the date part using `substring`: `"2024-11-16T10:30:01.001Z".substring(0, 10)"` which returns `"2024-11-16"`.

**Comment by jemid21** [comment]
Hello,

Thank you very much for your time and for the suggestion! I tried implementing your approach using JavaScript+Lodash in the Transform modal but unfortunately, I couldn’t get it to work. I also sought help from ChatGPT, and here’s the code I tried based on the recommendations:

// Verify the JSON is a valid object
if (typeof json === 'object' && json !== null) {
  // Transform the date keys to remove the time
  for (let doctor in json) {
    let transformedDates = {};
    for (let dateTime in json[doctor]) {
      // Keep only the date part (YYYY-MM-DD)
      const dateOnly = dateTime.split(' ')[0];
      transformedDates[dateOnly] = json[doctor][dateTime];
    }
    json[doctor] = transformedDates; // Replace with the new date keys
  }
  return json; // Return the transformed JSON
} else {
  throw new Error("The loaded JSON is not a valid object.");
}

I ensured to switch to JavaScript+Lodash mode as per your instructions, but I kept encountering errors or issues with the transformation. Could you kindly guide me further or let me know if I misunderstood something?

Thank you again for your help, and I really appreciate your time!

Best regards,

**Comment by josdejong** [comment]
It can be really valuable to spend some time learning JavaScript and Lodash rather than asking ChatGPT. I think actual understanding and experience brings you further than a "glorified autocomplete" 😉.

Here is a query that will remove the `" 00:00:00"` part of your nested keys:

```js
// JavaScript + Lodash
function query (data) {
  return _.mapValues(data, planning => _.mapKeys(planning, (_, key) => key.substring(0, 10)))
}
```

In your specific case though, I think you can also safely do a simple replace all in the text, replacing `" 00:00:00"` with an empty string.


For reference, here the structure of the document that you shared privatedly with me:
```js
{
  "NAME1": {
    "2025-01-06 00:00:00": "ACTION 1",
    "2025-01-07 00:00:00": "ACTION 2",
    "2025-01-08 00:00:00": "ACTION 3",
    ...
  },
  "NAME2": {
    "2025-01-06 00:00:00": "ACTION 1",
    "2025-01-07 00:00:00": "ACTION 2",
    "2025-01-08 00:00:00": "ACTION 3",
    ...
  },
  ...
}
```

**Comment by josdejong** [comment]
Good to hear, you're welcome 😄👍.

**Comment by josdejong** [comment]
I've added functions to JSON Query to work with objects (`mapObject`, `mapKeys`, `mapValues`) and strings (`join`, `split`, `substring`, `number`, `string`). This makes it possible to do your query with [JSON Query](https://jsonquerylang.org/). It looks like:

```js
mapValues(mapKeys(substring(get(), 0, 10)))
```
(here `get()` is to get the current key into the function `substring`)
