### ISSUE TITLE
esm-env warning

### ISSUE THREAD

**Issue by bdbvb** [josdejong/svelte-jsoneditor#507]
I'm seeing the following console warning when loading my app that uses vanilla-jsoneditor (2.3.2), bundled using Vite.

**If bundling, conditions should include development or production. If not bundling, conditions or NODE_ENV should include development or production. See https://www.npmjs.com/package/esm-env for tips on setting conditions in popular bundlers and runtimes.**

That warning points to esm-env, which is used by svelte, which is used by vanilla-jsoneditor.

Any thoughts on how I can address that warning?

Thanks!

**Comment by josdejong** [comment]
Yeah, I noticed it myself too, after updating the vite and svelte dependencies. I had to add some extra configuration in the Rollup config that creates the vanilla bundle.

This issue has been fixed now in `v2.2.3`.
