### ISSUE TITLE
How to import bundle from plain JS

### ISSUE THREAD

**Issue by Mark-81** [josdejong/svelte-jsoneditor#53]
I want to use this library in a small PHP/JS project.
Reading the docs I'm trying to follow the examples for plain javascript.

This line:

    import { JSONEditor } from 'svelte-jsoneditor'

does not work because the browser (Firefox) requires the module name starts with `/`, `./` or `../`.
So I changed it to an absolute path:

    import { JSONEditor } from '/node_modules/svelte-jsoneditor/dist/jsoneditor.js'

Now I have a 404 (even the path is correct - PHP Storm can retrieve the file) and another error:

> Loading module from “http://mydevice.local/node_modules/svelte-jsoneditor/dist/jsoneditor.js” was blocked because of a disallowed MIME type (“text/html”).

I copied and paste [this](https://github.com/josdejong/svelte-jsoneditor/blob/main/examples/browser/basic_usage.html) example in my HTML page. I only adjusted the path of the module to match the actual position on my machine.

Again, if I copy to the bundle file to `/js/jsoneditor.js` and change the include to a common script tag like this:

    <script type="text/javascript" src="/js/jsoneditor.js">

I get this error:

> Uncaught SyntaxError: export declarations may only appear at top level of a module [jsoneditor.js:55:43779](http://mydevice.local/js/jsoneditor.js)

**Comment by josdejong** [comment]
I suppose you have to make sure the dist/jsoneditor.js file is hosted correctly by your PHP backend, and can be fetched by the frontend. So first make sure your version of the url `/node_modules/svelte-jsoneditor/dist/jsoneditor.js` actually works, you can try if you can load this in your browser and see if it returns the JavaScript bundle. Alternatively, you can load the bundle from a CDN if that is acceptable for your project.

Here is a working example that fetches the bundle from a CDN: https://jsbin.com/zotiler/edit?html,output

**Comment by josdejong** [comment]
> Again, if I copy to the bundle file to `/js/jsoneditor.js` and change the include to a common script tag like this:
> 
> ```
> <script type="text/javascript" src="/js/jsoneditor.js">
> ```
> 
> I get this error:
> 
> > Uncaught SyntaxError: export declarations may only appear at top level of a module [jsoneditor.js:55:43779](http://mydevice.local/js/jsoneditor.js)

You cannot load the library like `<script type="text/javascript" src="/js/jsoneditor.js">`, it is an ES module, see demo linked above.
