### ISSUE TITLE
Support tabs for indentation

### ISSUE THREAD

**Issue by Roy-Orbison** [josdejong/svelte-jsoneditor#55]
Please add a checkbox to the **Configure indentation** dialogue so that the editor can use literal tabs. When checked, use the number to set [tabSize][0], but set [indentUnit][1] to a single tab character, rather than `tabSize` × space characters.

[0]: https://codemirror.net/6/docs/ref/#state.EditorState%5EtabSize
[1]: https://codemirror.net/6/docs/ref/#language.indentUnit

**Comment by josdejong** [comment]
Thanks for your suggestion Roy, makes sense 👍

**Comment by josdejong** [comment]
Support for tabs is available now in `svelte-jsoneditor@0.3.60` and web application `v6.3.1`.
