### ISSUE TITLE
Default tree mode is not understandable

### ISSUE THREAD

**Issue by zeynepatess** [josdejong/svelte-jsoneditor#59]
All indents are coming as expanded in default. If there is an tree mode button, people better understand how to collapse all indents and display in the tree mode. I had to read the documentation for not leaving JSON editor. It was the fastest, most convenient tool I've been using, I had difficulty with the tree mode. This is a feedback, hope you keep doing great work!

P.S: I'll try to use all new features through time

**Comment by josdejong** [comment]
Thanks for your feedback @zeynepatess 👍 

So if I understand you correctly, in the new editor it is hard to discover how to toggle between `code` and `tree` mode?

**Comment by josdejong** [comment]
I see I had changed the default to show a tree editor in both panels. I've reverted that now to open a code editor in the left panel and tree editor in the right panel again the first time you open the application, which was the default in the old editor. Does that address your issue?

As for formatting/compacting your JSON in tree mode: in tree mode, the data is always rendered in a neatly formatted way. When you copy or save your JSON document, you can choose whether you want the data formatted or compacted.

**Comment by josdejong** [comment]
@zeynepatess any more feedbacks? If not I'll close this issue assuming that it is solved.

**Comment by zeynepatess** [comment]
Unfortunately I had no time for reply, I'll check your answers today,
thanks for support !

19 Nis 2022 Sal 10:49 tarihinde Jos de Jong ***@***.***> şunu
yazdı:

**Comment by zeynepatess** [comment]
Hi @josdejong , yeah this improvement covers most of the issue! Thank you. 
I do not remember well, but in the old editor, was the default tree mode displaying all objects as collapsed or expanded? 
New editor displays the JSON as expanded. Maybe for the default mode, closing them might be better (so that users can see what is down there at the bottom of the screen)

This is just a recommendation, thanks for allowing feedback, love working with this tool.

**Comment by josdejong** [comment]
Thanks, good to hear 👍 

You're right, the new editor expands more by default, and it fully expands small documents. I noticed myself very often having to click the "Expand all" button right after opening a document. I suppose it depends on what you're going to do: do you just want to see what is in the document, then you want to expand all. But if you want to explore a large document it works better to start with expanding just the root node/array, and then one by one expand the paths you where looking for. I guess there is no silver bullet here, but I would love to hear other peoples opinions/needs on this. 

I'll close this issue now. Please reopen or create a new one if you have more ideas/suggestions.
