### ISSUE TITLE
Select content within brackets using double click

### ISSUE THREAD

**Issue by remondulos** [josdejong/svelte-jsoneditor#60]
In classic mode I could select the content within brackets by double clicking the text within the brackets (content only) or in front of the brackets (content + brackets). This is not working anymore. Will this feature be implemented in the new version as well?

**Comment by josdejong** [comment]
Thanks for your feedback Remon. I didn't know about this feature of the Ace editor used in the classic version of JSONEditor. 

It would be nice to see if we can configure this in Code Mirror 6 editor or implement a plugin or something to get this behavior.

Help would be welcome, anyone interested in looking into this?

**Comment by josdejong** [comment]
@remondulos I did some experiments, and it is possible to perform an action when double-clicking right from a bracket `{` or `[`. I could implement to either select the contents+brackets then, or select the contents only. 

Do you use both these cases, or only one of the two? Which one of the two is most important to you?

**Comment by remondulos** [comment]
@josdejong Thanks for your reply. I mostly use it for selecting the content within the brackets, but selecting the content including the brackets would be nice to have. It's very efficient for multiplying objects within the json.

**Comment by josdejong** [comment]
👍 good to know.

What I will do is implement selecting contents only when double-clicking _right_ from a bracket now, there is an easy solution for that. 

I will keep this issue open to investigate whether it's also possible to select contents+brackets when double-clicking _on top of_ a bracket. I didn't yet find a solution for that. Help would be welcome to figure that out.

**Comment by josdejong** [comment]
Double-click right from a bracket to select the contents is now available in `svelte-jsoneditor@0.3.38`, web application `v6.0.4`

**Comment by josdejong** [comment]
I'll close this issue now. If anyone feels the need to improve on this further please let me know.
