### ISSUE TITLE
Bug: unexpected delete

### ISSUE THREAD

**Issue by krlee227** [josdejong/svelte-jsoneditor#64]
If I click other than the pull-down button after editing keyword or content in a object, the object disappears in total.

**Comment by josdejong** [comment]
Thanks for reporting Kwang-Ryeol Lee, that sounds odd indeed. How can I reproduce your issue exactly? 

Do you mean that when you have selected a value inside an object, and you press Delete, that both key and value are removed?

**Comment by josdejong** [comment]
I'll close this issue now, can't do anything without more information. @krlee227 please reopen this issue if you have more information.
