### ISSUE TITLE
Transpile bundle to support older JavaScript environments

### ISSUE THREAD

**Issue by bigbigmyworld** [josdejong/svelte-jsoneditor#67]
For some reason svelte-jsoneditor@0.3.40 can not  compiling  when use npm:

✖ [14:12:16] 1 error in compiling process.
[error] in ./~/svelte-jsoneditor/dist/jsoneditor.js
Module parse failed: /Users/haha/dev_code/demo/vendors/node_modules/svelte-jsoneditor/dist/jsoneditor.js Unexpected token (1:17468)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (1:17468)
 @ ./client/components/ScSvelteJSONEditor/SvelteJSONEditor.js 6:24-52

need help ,thanks!!

**Comment by josdejong** [comment]
Thanks for reporting. I see at `1:17468` in `dist/jsoneditor.js` that there is a spread operator `...`. The TypeScript+Rollup bundling right now targets `es2019` and doesn't do much transpilation. We can have a look on whether we can make a bundle to support older JS environments too, or transpile the existing bundle into ES5 or something.

**Comment by josdejong** [comment]
I think this has been addressed via #85, published in `svelte-jsoneditor@0.3.56`. Will close this issue now
