### ISSUE TITLE
Can't find a way to reformat the code view

### ISSUE THREAD

**Issue by eareg** [josdejong/svelte-jsoneditor#68]
In the old version, I can paste in some JSON, click on TREE, then click back on CODE, and it is all nicely formatted for me.
In the new version, it just restores my unformatted JSON.

Switching to the old view because of this.

**Comment by eareg** [comment]
Never mind!  I found it.  I was just so used to reformatting by changing the view, my eyes went right over it, even when I was looking for it.

**Comment by josdejong** [comment]
Good to hear you found the "Format" button 👍 

You can also format using the quick key `Ctrl+I`
