### ISSUE TITLE
Line 24: Unexpected token ... while parsing file: /node_modules/svelte-jsoneditor/dist/jsoneditor.js

### ISSUE THREAD

**Issue by on2air** [josdejong/svelte-jsoneditor#7]
I'm trying to install this into an environment that I don't have much control over and getting this error.  I know that the spread operator is available in my codebase as I use it plenty, so not sure why it would complain about that.

Any ideas what could be causing this?

**Comment by josdejong** [comment]
I guess you're environment does not like usage of the spread operator. A solution would be to either change the setup so it accepts usage of the spread operator. It may also be an idea to generate a version of `svelte-jsoneditor` for older environments and compile it down to ES5 or something like that (for reference: https://github.com/rollup/rollup/issues/354).

**Comment by on2air** [comment]
I don't think that is it as I use the spread operator and other libraries I use also use it.  Could it be that the environment I am using only supports UMD formatted bundles and not ES modules?  Are you only bundling as an ES module?

**Comment by on2air** [comment]
it appears to be coming from your bundled lodash in the dist/jsoneditor.js  . I already have lodash in my package.json and use it just fine so don't think its the code.  Not sure why.  Do you need to bundle in lodash with your bundle?

**Comment by josdejong** [comment]
Right now there are two bundles generated: UMD and ES. But this needs more attention but all of that may need some attention (I'm sort of awaiting what sveltekit will bring before spend effort there).

**Comment by on2air** [comment]
seems like your bundle has a lot of 3rd party libs in it (lodash, classnames, fontawesome). It makes the bundle pretty big which in the environment im trying to get it running it will be an issue.  Is there a way to not bundle in all the 3rd party libs?

**Comment by josdejong** [comment]
I guess the idea of a _bundle_ is to bundle everything 😉 . Besides the bundles we'll need to export non-bundled code as well, I think that's what you're looking for. I haven't spend much time getting that sorted out (awaiting SvelteKit).

**Comment by on2air** [comment]
yeah, typically most libs (as far as I understand, but im not an expert in building packages) have a lib/* folder that has the compiled js associated with that lib, and the dist/ is usually for static files like css, images, etc.  and then when they get imported into the application, the parent app handles all the dependencies and does the final bundle of all libraries.  But looks like you just have the full bundles available for now.  Sounds good, I understand you have to see what SvelteKit does in that regard.  I don't think I can use it in current state, but I'll try it again down the road if you get that figured out. thx

**Comment by josdejong** [comment]
👍 

Help would be welcome btw, setting all up properly.

**Comment by josdejong** [comment]
I think this issue is solved now, since `v0.1.2`: for Svelte, the library is now pointing to the source code. This requires you to set up some additional configuration in order to use the library, see readme: https://github.com/josdejong/svelte-jsoneditor#svelte-setup. It seems to be the preferred way of doing things in Svelte.

Will close this issue now, please reopen if there is still an issue.
