### ISSUE TITLE
shift+enter for previous search result

### ISSUE THREAD

**Issue by dranitski** [josdejong/svelte-jsoneditor#70]
![image](https://user-images.githubusercontent.com/27373393/165518832-fd567763-f5f1-41c7-b489-73b39d5e905b.png)

it would be great if `SHIFT+ENTER` key combination will show previous search result as it works in Chrome, Vscode and everywhere, i guess.

Thanks in advance!

**Comment by josdejong** [comment]
Thanks, good point. It's implemented (not yet published)
