### ISSUE TITLE
Difference from https://github.com/josdejong/jsoneditor?

### ISSUE THREAD

**Issue by zehawki** [josdejong/svelte-jsoneditor#71]
Thank you for this brilliant library. Ive been a long time user of jsoneditoronline.org (its a pinned tab since I use it all the time 😁).

Would be good to have some documentation as to **how** this package is different from your previous lib (https://github.com/josdejong/jsoneditor) and also **why** you decided to create another.

I also see that the demo for the earlier is pointing to **_http_**://jsoneditoronline.org/ while the latter is pointing to **_https_**://jsoneditoronline.org/, but both seem to be running off svelte-jsoneditor as per the changelog.

**Comment by zehawki** [comment]
Ok I see this https://github.com/josdejong/jsoneditor/issues/1223

**Comment by josdejong** [comment]
Thanks Amit, glad to hear you like it!

Yes, in https://github.com/josdejong/jsoneditor/issues/1223 a lot of the thoughts behind this are discussed, but it is a lengthy discussion. I do like your idea though, for example to write a section in the readme of `svelte-jsoneditor` about this. It can help having a bit of context.

**Comment by josdejong** [comment]
@zehawki I've written a section explaining the differences: https://github.com/josdejong/svelte-jsoneditor#differences-between-josdejongsvelte-jsoneditor-and-josdejongjsoneditor

Does this clarify things?

**Comment by zehawki** [comment]
Its quite perfect, thank you. Maybe add a row on bundle size & dependencies if you like?

**Comment by josdejong** [comment]
Ok 👍 

Hmm. The bundle size and dependencies are tricky: they will probably change over time, I prefer not to list them there.
