### ISSUE TITLE
Minor UI thingies, running list

### ISSUE THREAD

**Issue by zehawki** [josdejong/svelte-jsoneditor#74]
1. 
In code mode, the toolbar should show whether the current setting is `format` or `compact`.
In tree mode, the toolbar should show whether the current setting is `expand` or `collapse`.

Though I understand it may not be possible since those are not states, but actions.

2. Tree mode should not show background color - I always find myself clicking outside somewhere trying to get rid of the "selection" highlight. So its a bit confusing and reduces readability. (What was its purpose BTW?)

**Comment by zehawki** [comment]
2 - I think you are right. Here's how its on https://jsoneditoronline.org/

![image](https://user-images.githubusercontent.com/8095144/165780850-0d330384-88e9-424f-9123-ee4e7ba2e00c.png)

vs in my current integrated version

![image](https://user-images.githubusercontent.com/8095144/165780944-edf48072-bebb-4e21-9d0d-b42aa0547e14.png)

**Comment by josdejong** [comment]
oooo ha ha, you mean the green background? 😂 That a feature: it shows the differences between the left and right panel, you can turn that on or off with the button between the panels.

**Comment by zehawki** [comment]
Damn... hahah, sorry, my stupidity.

**Comment by josdejong** [comment]
No problem 👍 😄

**Comment by josdejong** [comment]
So, about your point (1): does my explanation make sense? Ok to leave it as it is right now?

**Comment by josdejong** [comment]
Ok! Thanks for your inputs, keep them coming, it's good have a fresh mind and keep thinking out of the box :)
