### ISSUE TITLE
Unable to load a JSON via URL if it contains a URL-encoded string

### ISSUE THREAD

**Issue by tonicboy** [josdejong/svelte-jsoneditor#76]
When trying to make use of JSON loading via URL (https://jsoneditoronline.org/docs/index.html#url), the process fails if one the values being passed is itself URL encoded.

### Steps to Reproduce:

1. Start with a JSON that contains URL-encoded content such as:
`'{"URL":"https://www.google.com/search?q=Hello%20World"}'`
2. Encode the JSON with encodeURIComponent, as per docs
3. Generate URL as https://jsoneditoronline.org/#left=json.ENCODED_JSON_CONTENTS

### Expected Behavior

1. Presented with jsoneditor window that looks like this:
![image](https://user-images.githubusercontent.com/4170176/166858202-5e069f7e-559b-48b1-97e1-7399415e2b56.png)

### Actual Behavior

1. Presented with jsoneditor window where URL-encoded value has been decoded, like this:
![image](https://user-images.githubusercontent.com/4170176/166858327-031e8e64-a3e4-4c28-aadd-29195cbc77e4.png)

**Comment by josdejong** [comment]
Thanks for reporting. It looks like the contents is decoded twice or so. Will look into it

**Comment by josdejong** [comment]
This has been fixed now in `v6.0.9` of the web application, the JSON contents from the URL was indeed accidentally decoded twice.

For reference, the example url with encoded JSON contents is:

https://jsoneditoronline.org/#left=json.%7B%22URL%22%3A%22https%3A%2F%2Fwww.google.com%2Fsearch%3Fq%3DHello%2520World%22%7D
