### ISSUE TITLE
Programatically set value?

### ISSUE THREAD

**Issue by cloakedninjas** [josdejong/svelte-jsoneditor#77]
With the old Ace editor you could do the following:

```
const el = document.querySelector('.ace_editor');
window.ace.edit(el).setValue('{"foo": "bar"}');
```

And [it seems](https://stackoverflow.com/questions/21844574/programmatically-edit-codemirror-contents-without-access-to-object) CodeMirror supports 

```
el.CodeMirror.setValue('{"foo": "bar"}')
```

... but this isn't working. Is there an equivalent now? Our use-case is Cypress integration tests - we need to interact with the editor in the context of a user / JS console where we can programatically set the value without having access to JSONEditor instance

**Comment by josdejong** [comment]
Good question. 

First, `svelte-jsoneditor` uses [CodeMirror 6](https://codemirror.net/6/), which has a different API than the previous versions of CodeMirror.

I'm not sure if there is a way to find the CodeMirror instance via the HTML DOM. If you _do_ have the code mirror instance, you can dispatch updated text via `codeMirrorView.dispatch({ changes: { from: 0, to: newText.length, insert: newText }})`, though I expect that this will not trigger an "update" of `svelte-jsoneditor` as you would get when a user enters text. To really simulate the input of a user you would have to simulate key presses I guess, not sure if that is possible.
