### ISSUE TITLE
export 'JSONEditor' was not found in 'svelte-jsoneditor'

### ISSUE THREAD

**Issue by lsbyerley** [josdejong/svelte-jsoneditor#8]
I am looking to use this new beta editor in a react application (not create-react-app) and was following this issue about wrapping it in a react wrapper https://github.com/josdejong/svelte-jsoneditor/issues/4

When i try to use the codesandbox posted in that issue above, i get the following error:

```
export 'JSONEditor' (imported as 'JSONEditor') was not found in 'svelte-jsoneditor' (module has no exports)
```

importing like so:

```
import { JSONEditor } from "svelte-jsoneditor";
```

Do you know why this could be happening? Webpack is being used to compile

**Comment by josdejong** [comment]
The code sandbox itself works, right? https://codesandbox.io/s/svelte-jsoneditor-react-59wxz?file=/src/App.js

I guess it depends on your webpack setup. How can I reproduce your issue?

You could try use one of the two bundles specifically instead of having your setup resolve them: 

```js
// automatically pick the right type of bundle
import { JSONEditor } from "svelte-jsoneditor";

// use the UMD bundle
import { JSONEditor } from "svelte-jsoneditor/dist/jsoneditor.js";

// use the ES bundle
import { JSONEditor } from "svelte-jsoneditor/dist/jsoneditor.mjs";
```

**Comment by lsbyerley** [comment]
Thank you for the response.. yes the codesandbox does work.

I guess my webpack config needs a change as using the es bundle does work for me. Thank you for posting that

```
import { JSONEditor } from "svelte-jsoneditor/dist/jsoneditor.mjs";
```

**Comment by josdejong** [comment]
Ah, good to hear that works for you 👍 . So apparently your setup was picking the `jsoneditor.js` instead of `jsoneditor.mjs` for some reason. 

Will close this issue.

**Comment by lsbyerley** [comment]
I seem to be having an issue now where clicking any of the buttons in the navbar for the editor makes the whole page reload. Have you encountered this before?

I'm seeing the `handleMouseDown` event being fired in the console and then the page reloads.

I can create another issue for this if you think its helpful

**Comment by josdejong** [comment]
Hm that sounds odd. Is it possible for you to create a minimal example demonstrating this issue? That will help figuring out where the problem comes from.
