### ISSUE TITLE
make search results toggle or clear node path

### ISSUE THREAD

**Issue by dranitski** [josdejong/svelte-jsoneditor#81]
Hi! It is sometimes confusing if I have one node selected and toggle search, then cycle through search results.
I think "selected node path" should be dropped at least, and it will be great if "selected node path" will follow the current selected search result, it would be super handy. 

![image](https://user-images.githubusercontent.com/27373393/168784419-990c48cd-8af3-41ca-841c-95341086496e.png)

Case:
user searches for word "social" in a big json. Cycling through search results with auto-selecting current search result would be super handy since user could easily (without extra X clicks) see which json section (node path) is a parent of current search result.

Thanks in advance!

**Comment by josdejong** [comment]
I've now implemented and published a fix that clears the navigation path whilst iterating through search results. Keeping the selection in sync with the active search results works out a bit odd (mixing two different things). Another future improvement could be to implement Ctrl+Click to switch focus from the SearchBox to the active search result for real.
