### ISSUE TITLE
Compile error on 0.3.53 - Could not resolve '../utils/typeUtils.ts'

### ISSUE THREAD

**Issue by aam-git** [josdejong/svelte-jsoneditor#84]
Just updated package with latest sveltekit, but now getting this error

> Could not resolve '../utils/typeUtils.ts' from node_modules/svelte-jsoneditor/logic/selection.js
    at error (/usr/src/app/node_modules/rollup/dist/shared/rollup.js:198:30)
    at ModuleLoader.handleResolveId (/usr/src/app/node_modules/rollup/dist/shared/rollup.js:22508:24)
    at /usr/src/app/node_modules/rollup/dist/shared/rollup.js:22471:26

Rolled back to 0.3.52 and its fine again

**Comment by josdejong** [comment]
Thanks for reporting. I'm in the middle of converting the library to TypeScript, but it's not a smooth ride 😅 . Will fix it.

**Comment by aam-git** [comment]
> Thanks for reporting. I'm in the middle of converting the library to TypeScript, but it's not a smooth ride 😅 . Will fix it.

No worries, i'll sign up to follow releases and try again on your next update.  

Nice work so far by the way :)

**Comment by josdejong** [comment]
Thanks, good to hear 😄

**Comment by josdejong** [comment]
This should be fixed now in `v0.3.54`

**Comment by aam-git** [comment]
looks good here
