### ISSUE TITLE
Feature request: sort arrays for compare

### ISSUE THREAD

**Issue by HaanJde** [josdejong/svelte-jsoneditor#87]
Title says it all.

Unsorted arrays consisting of complicated objects makes it hard to compare them. I know json by it's nature is unsorted but it's users are human.

Thank you for your hard work, really makes a difference.

**Comment by josdejong** [comment]
Thanks for your suggestion. Do you mean you want to sort object keys, or arrays? Sorting object keys can make sense, and the order does not have a meaning. Sorting an array though _does_ change the data for real, the array order does have meaning. Also, if you want to sort an array containing objects, you as a user will have to specify by which property you want to sort. You can do that with the Sort Modal or Transform Modal. 

> Thank you for your hard work, really makes a difference.

Thanks, glad to hear :)

**Comment by HaanJde** [comment]
> "... can do that with the Sort Modal or Transform Modal."

Didn't realize that. Thanks for the suggestion.

You can close this.

**Comment by josdejong** [comment]
👍
