### ISSUE TITLE
Can't seem to switch between readonly and editable

### ISSUE THREAD

**Issue by jseparovic** [josdejong/svelte-jsoneditor#92]
I can't seem to figure out how to toggle between readonly and editable states after the Editor has been rendered.

I'm trying:
```
  useEffect(() => {
    if (editor.current) {
      console.log("updateProps", { readonly: disabled });
      editor.current.updateProps({ readonly: disabled });
    }
  }, [props, disabled]);
```

But it doesn't seem to do anything. The Editor remains in the same initial state.

Here is the sandbox link:
https://codesandbox.io/s/blue-cloud-i4vo7?file=/src/JSONEditor.tsx:3256-3458

**Comment by josdejong** [comment]
There is a typo in the naming of the option, it is `readOnly`, not `readonly`.

**Comment by jseparovic** [comment]
lol, of course! Thanks for that. Cheers
