### ISSUE TITLE
How to import style?

### ISSUE THREAD

**Issue by JonnyLeiZhang** [josdejong/svelte-jsoneditor#93]
Hi @josdejong ,
Compared to jsoneditor, svelte-jsoneditor doesn't have jsoneditor.css file under dist folder.
In my project I need to import that to make style take effect. (And unfortunately only css is supported.)

Do you know any workaround for this? Or is it possible to bundle css for svelte-jsoneditor aslo?

BR/Lei

**Comment by josdejong** [comment]
The CSS styling of `svelte-jsoneditor` is bundled with the JavaScript code. There is no need to load an additional jsoneditor.css file.

You can customize the styling using CSS variables, see docs: https://github.com/josdejong/svelte-jsoneditor#styling

**Comment by JonnyLeiZhang** [comment]
Thanks @josdejong, now I can see these styles.
But I got one strange problem in tree mode, all the operations cannot work.
![image](https://user-images.githubusercontent.com/45590945/172314038-c4df79a4-6ee3-45d3-a860-7907d5569bdf.png)
And I can manually add some items, but it still feels strange, I don't know why
![jsoneditor](https://user-images.githubusercontent.com/45590945/172315451-c5eebd00-ebf8-4293-b8c0-06e6d17edcce.gif)

**Comment by josdejong** [comment]
Maybe you're hitting the issue described in #49?

**Comment by JonnyLeiZhang** [comment]
> Maybe you're hitting the issue described in #49?

Yeah I guess it's same issue.
