### ISSUE TITLE
[Violation] Added non-passive event listener to a scroll-blocking [] event.

### ISSUE THREAD

**Issue by alesf** [josdejong/svelte-jsoneditor#94]
I'm using a standalone bundle with Vue and I get loads of these warnings in Chrome:

[Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952 

Events they're referring to are touchstart and touchmove.

**Comment by alesf** [comment]
You are right. I never thought to look trough dependencies.
It seems the issue is inside a @codemirror/view.
Update to @codemirror v6 doesn't seem to fix the issue.
I'll try to report an issue there.

**Comment by josdejong** [comment]
Yes I think so. Thanks.

I just noticed that in Firefox I get the following console warning as soon as I scroll a bit up and down in CodeMirror (sorry in Dutch, the link points to an English document though): 

> Deze website lijkt een ‘scroll-linked’ positioneringseffect te gebruiken. Mogelijk werkt dit niet goed met asynchrone panning; zie https://firefox-source-docs.mozilla.org/performance/scroll-linked_effects.html voor verdere details en het bijdragen aan de discussie over gerelateerde hulpmiddelen en functies!

**Comment by josdejong** [comment]
I'll close this issue here, I think it's not actionable since it originates in the CodeMirror editor
