### ISSUE TITLE
is there an event or callback function when we click an node 

### ISSUE THREAD

**Issue by hfutyezi** [josdejong/svelte-jsoneditor#95]
i want to do someting when we click an node or path.

**Comment by josdejong** [comment]
There are no callbacks for that available. It can make sense to implement an API like that.

Can you explain what you want to do when the user clicks somewhere?

**Comment by hfutyezi** [comment]
> There are no callbacks for that available. It can make sense to implement an API like that.
> 
> Can you explain what you want to do when the user clicks somewhere?
copy the jsonpath and send it to server.

**Comment by hfutyezi** [comment]
For example
1、copy the jsonpath and send it to server.  
2、show an modal dialog ,and we can use jsonpath to do something.

**Comment by hfutyezi** [comment]
i have reslove this problem by other way.thank you
