### ISSUE TITLE
CSS bug: error toast is hard (impossible) to read

### ISSUE THREAD

**Issue by nanny07** [josdejong/svelte-jsoneditor#97]
Event with Light or Dark theme it's hard to read

![image](https://user-images.githubusercontent.com/17173586/173371750-4c9c65c5-f58d-4d31-b8aa-5545247a4e17.png)

**Comment by josdejong** [comment]
Thanks for reporting, the `code` accidentally got an a global CSS background color that was almost white.

Fixed now in web application v6.3.2 (you may need to refresh your browser).
