### ISSUE TITLE
navigator.clipboard is undefined on non-secured orgin (http)

### ISSUE THREAD

**Issue by hfutyezi** [josdejong/svelte-jsoneditor#98]
i found this problem when my website is not https ,and some browser will have this error.
navigator.clipboard  return undefined

**Comment by hfutyezi** [comment]
My action is to copy text

**Comment by josdejong** [comment]
Ah, that's interesting. For security reasons, `navigator.clipboard` is not available when you're on a non-secure connection.

I see a workaround here that may work: https://stackoverflow.com/a/33928558/1262753

**Comment by josdejong** [comment]
The fix by @cloydlau has been published in `v0.7.5`, thanks again.
